### ISSUE TITLE
Detect while True: else statements

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#100]
vulture currently detects the case when a `else` block is associated with an `if True` statement, but does not do so in the case of a `while` loop.

For example, the following example wouldn't be detected as unused code:
```py
while True:
    print("Hi")
else:
    # Dead code
    print("Dead code")
```

**Comment by jendrikseipp** [comment]
Good catch!

**Comment by RJ722** [comment]
I would like to submit a PR. 😄

**Comment by jendrikseipp** [comment]
Perfect!
