### ISSUE TITLE
Add CONTRIBUTING.rst

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#101]
Add a CONTRIBUTING.rst file to [vulture](https://github.com/jendrikseipp/vulture). It should include the following information:
* How to setup a virtual environment?
* How to install the development version of vulture?
* Coding standards
    - Ensure that people send a PR from a branch other than the `master` branch.
    - How to name the branches?
* How to send a Pull Request?
* Be polite and wait for reviews
* Take feedback positively!

An example may be found here: https://coala.io/newcomer

**Comment by jendrikseipp** [comment]
Good idea!

**Comment by RJ722** [comment]
I forgot, it should also contain instructions on how to
* Install `tox`
* Run tests locally.
