### ISSUE TITLE
Missing check of script files because not ends with .py

### ISSUE THREAD

**Issue by estevopaz** [jendrikseipp/vulture#105]
Hi, please feel free to include my code if you wish:

    def is_python(file_path):
        '''Check if file is a python file.'''
        if os.path.isfile(file_path) is False:
            return False
        if file_path.endswith('.py'):
            return True
        # Check also html files because Jinja templates
        if file_path.endswith('.html'):
            return True
        _, extension = os.path.splitext(file_path)
        if extension != '':
            return False
        file_open = open(file_path)
        first_line = file_open.readline(50)
        file_open.close()
        if '#!'in first_line and 'python' in first_line:
            return True
        return False

**Comment by RJ722** [comment]
Hi @estevopaz!

Currently, we are using just one check: `path.endswith('py')`, which is mostly sufficient. I haven't really thought of the idea of checking a shebang, it looks good, but is it really required?
What are the possible scenarios where a file might have shebang, but does not ends with `.py`?

Thank You for your contribution!

**Comment by jendrikseipp** [comment]
I think there are too many corner cases for this to work reliably automatically. In my opinion it's best to list the files that are not ending with .py manually (or with bash glob patterns).

**Comment by estevopaz** [comment]
Ok, thanks for replay.
And no, in my case just .py is not enough.
In our projects, all under bin/ and installed into system by setup.py is without .py extension.
I don't see a problem check if a file starts with "#!/usr/bin/python3" for instance, but I respect your decision.
