### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by sobolevn** [jendrikseipp/vulture#106]
Hello, thanks for the awesome package!

I have a few questions/suggestions:

1. What is the way to configure `vulture`? As I get it now the only possible way is command line arguments. Which can be rather long or complex. A common way to configure something in `python` is supporting both `.vulture.ini` and `setup.cfg`. I personally prefer `setup.cfg`.
2. Is it possible to ignore some lines from audit? For example, I use [`better-exceptions`](https://github.com/Qix-/better-exceptions) sometimes. It only requires to write `import better_exceptions`. I can ignore this line from `pylint`/`flake8` by using `import better_exceptions  # noqa` instead. As I can understand right now it is not supported.

Thanks!

**Comment by RJ722** [comment]
Hi @sobolevn!
> What is the way to configure vulture? As I get it now the only possible way is command line arguments. Which can be rather long or complex. A common way to configure something in python is supporting both .vulture.ini and setup.cfg. I personally prefer setup.cfg.

Yes, indeed, command line options are the only way to configure vulture right now. Having a `.vulture.ini` file would be an overkill IMHO for such a simple task. You can always use aliases if you find the commands are too long.

> Is it possible to ignore some lines from audit? For example, I use better-exceptions sometimes. It only requires to write import better_exceptions. I can ignore this line from pylint/flake8 by using import better_exceptions # noqa instead. As I can right now it is not supported.

To avoid it being detected as dead code, you can whitelist `better_exceptions`, just create an additional file named `whitelist.py` (or whatever you wish to name it - it doesn't matter):
```py
from vulture.whitelist_utils import Whitelist

whitelist = Whitelist()
whitelist.better_exceptions
```

Just make sure to include this file when you run vulture, for ex.
```
vulture your_file.py whitelist.py
```

You won't need to explicitly mention this if `whitelist.py` appears in your root folder.

**Comment by sobolevn** [comment]
Thanks for the quick answer.

`whitelist` solves this issue, but again: I have to do several things to configure several different tools to ignore the single line. 

1. Configure `flake8` with `# noqa` comment
2. Configure `vulture` with `whitelist.py` in root folder

It seems that supporting `# noqa` (or similar), which is very popular among python developers, would make your API more friendly. Here are some example too illustrate my point from different similar libraries:
1. [`mypy`](https://github.com/python/mypy/issues/500)
2. [`pylint`](https://stackoverflow.com/questions/28829236/is-it-possible-to-ignore-one-single-specific-line-with-pylint)

**Comment by jendrikseipp** [comment]
Point taken, but I consider it a strength of Vulture that you don't have to litter the code with comments or workarounds. Other tools may not have the possibility of something like whitelist files, which is probably why they resort to such measures like `# noqa`. Personally, I believe that stuff like this decreases code readability.

**Comment by i25959341** [comment]
I dont see a problem at all with code readability using `noqa`

**Comment by Jay2109** [comment]
Is there any way to configure vulture such that it avoids serializer methods, authentication classes variables ?
example : **admin.py: Unused function has_view_permission** it is showing up methods that are over ridden by my base admin class.
Basically I want a solid solution for Django as it has many builtin methods and we over ride many of them
