### ISSUE TITLE
Write script for generating whitelist (was: False Unused function - ignoring APIs)

### ISSUE THREAD

**Issue by AbdealiJK** [jendrikseipp/vulture#109]
I was using vulture for my flask based API and found that it marked every API function I had as a "unused function".

Example:
```
@app.before_request
def before_req():
    pass

@user_api.route('/api/users', methods=['GET'])
def get_all():
    pass

```

Is it possible to make it such that if a specific decorator is used (possibly a regex for this) we can ignore the result ?

In general flask applications will have Blueprints with the name `.*api\..*` (example: profile_api, user_api, book_api, etc.) and flask applications will be `.*app\..*` (example: flask_app, test_app, app, etc.)

**Comment by RJ722** [comment]
Hi @AbdealiJK! 

We tried building a default whitelist for popular web-frameworks, particularly flask and django, but we couldn't come up with anything definitive. But, this approach is quite intriguing, I had not thought about this earlier. Thank You for the suggestion! :-)

We currently use the following mechanism to know about what to ignore.
```py3
def _is_test_file(filename):
    name = os.path.basename(filename)
    return any(
        fnmatchcase(name, pattern)
        for pattern in ['test*.py', '*_test.py'])


def _ignore_class(filename, class_name):
        return _is_test_file(filename) and 'Test' in class_name


def _ignore_import(_filename, import_name):
    # Ignore star-imported names, since we can't detect whether they are used.
    return import_name == '*'


def _ignore_function(filename, function_name):
    return (
        _is_special_name(function_name) or
        (function_name.startswith('test_') and _is_test_file(filename)))


def _ignore_variable(filename, varname):
    """
    Ignore _ (Python idiom), _x (pylint convention) and
    __x__ (special variable or method), but not __x.
    """
    return (
        varname in IGNORED_VARIABLE_NAMES or
        (varname.startswith('_') and not varname.startswith('__')) or
        _is_special_name(varname))
```

From what I see, we can introduce regex for each one of them and have a common helper function to spit out the matches. We could then make this regex configurable either through a command line option or through `whitelist_utils`. 

I'd highly appreciate @jendrikseipp's opinion on this.

**Comment by AbdealiJK** [comment]
The regex would always be nice to make it more generic I guess.
But just want to mention that the edges for those 4 ignores would not help for flask APIs as we need a regex for the decorator.

**Comment by RJ722** [comment]
Oh yes, forgot about that. We would need an additional check in the `visit_FunctionDef` method. That won't be too tough. But, IMHO the main problem would be that for this level of customisation, command line arguments aren't very suitable. We would need something permanent, but we sure don't want config files. Configuration through `whitelist_utils` seems like a way, but we would need @jendrikseipp's consent for it.

**Comment by jendrikseipp** [comment]
You can already exclude specific files with the `--exclude` option.

I think the whitelisting could be made easier by generating an initial whitelist automatically and let users adapt it to their needs. Maintaining a list of regexes sounds tedious. Let me quote myself in a recent mail:

"I believe a different approach could be to let users run `coverage.py` (https://coverage.readthedocs.io/) on their code and create an XML report. Afterwards, we collect the names of used variables, functions, etc. (that belong to the user's project) from the XML file and create a whitelist file with the used names. In a second step we could only add the subset of used names that Vulture reports as unused. [...] The advantage is that it works for all projects and probably requires very little code."

**Comment by AbdealiJK** [comment]
Ah, I was thinking the user would maintain the list of regexes not you guys :)
The coverage idea sounds cool.

**Comment by RJ722** [comment]
The XML reported by coverage.py is of the form:
```
<?xml version="1.0" ?>
<coverage branch-rate="0" line-rate="0.75" timestamp="1524751600489" version="4.3.4">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/f0366e5e2cf18f111cbd61fc34ef720a6584ba02/htdocs/xml/coverage-03.dtd -->
	<sources>
		<source>/Users/rahuljha/Documents/test_everything_here</source>
	</sources>
	<packages>
		<package branch-rate="0" complexity="0" line-rate="0.75" name=".">
			<classes>
				<class branch-rate="0" complexity="0" filename="unused.py" line-rate="0.75" name="unused_class_var.py">
					<methods/>
					<lines>
						<line hits="1" number="1"/>
						<line hits="1" number="2"/>
						<line hits="1" number="4"/>
						<line hits="0" number="6"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>
```
It only gives information about the line number and not the name of the unused code. Also, I don't have a very good experience with line number approximations either - In this case, `unused.py` looks like following:

(The unused function starts at line no. 5)

```py3
def a(f):
	print(f)

@a
def b():
    pass
```

**Comment by jendrikseipp** [comment]
Hmm, interesting. I looked into this a bit and think we'll have to implement our own script for tracing which functions, attributes, variables, etc. are used. For this, I think we need to use `sys.settrace` (https://docs.python.org/3/library/sys.html#sys.settrace). The trace module does something similar (https://github.com/python/cpython/blob/3.6/Lib/trace.py) and also uses `sys.settrace` but it can only trace which functions are used.

**Comment by jendrikseipp** [comment]
We will also have to figure out how the tracer script can be called for web applications. Maybe @AbdealiJK knows how we could do this.

**Comment by jendrikseipp** [comment]
Interesting! I completely agree that we should use coverage.py for obtaining the names all used functions and variables if possible. However, I'm not sure how the file tracer in the Coverage API helps us. Maybe it's best to ask Ned directly :-)

@nedbat: We would like to find out the names of all functions, methods, classes, variables, etc. that are used during the execution of a Python program. Unfortunately, coverage.py only reports the line numbers (in the XML output) and it seems unnecessarily complicated to retrieve the names of Python objects given a Python file and line numbers. Can we somehow use coverage.py to give us the names of used Python objects, maybe via a plugin?

**Comment by nedbat** [comment]
Hey there! You will need a trace function.  Writing your own doesn't have to be complicated, though you are right there are details like subprocesses that can be a pain.  Writing a file tracer plugin could be a way to piggy-back on coverage.py.

Getting function names wouldn't be hard, since you can inspect the frame object in the trace function to get what you need.  Variables are harder.

You've noted that coverage.py reports line numbers, but then you say it's hard to go from line numbers to the information you need.  But you already are doing AST analysis.  Couldn't you use coverage.py's line numbers to index into the AST you already have, and then use your AST expertise from there?

**Comment by jendrikseipp** [comment]
That's a very good idea, @nedbat, thanks!

I think we should allow passing a coverage.py XML file to Vulture. Instead of reporting all unused code, we can then collect a list of false-positives, i.e, items that Vulture detects as unused but which are reported as used in the XML file (since we know the filename and line number for all items that Vulture detects as unused). Then we can output the false-positives in a format suitable for adding to a whitelist file.

Some implementation notes: Let's call the new parameter `--make-whitelist COVERAGE_XML_FILE` and use the following format for the whitelist, `myfunc  # foo.py:42: unused function 'myfunc'`.

**Comment by AbdealiJK** [comment]
Just thinking this through in my head...
If I have a file with:
```
def abc(a):  # unused function
    return a + 1
```
coverage will tell me the line 1 `def abc...` is executed but  line 2 `return ...` is not executed.

So, we need to check if all lines inside that function have been unused, not the definition line.

**Comment by jendrikseipp** [comment]
That's a good point! Unfortunately, I can't think of a simple solution that allows us to use the XML file output by coverage.py for all different types of unused code (variables, classes, functions, etc.).

**Comment by RJ722** [comment]
Let me suggest a hypotheses (which is probably wrong):

Let's say that we find a line which is reported as unused by coverage.py, and then we locate that element in the ast. If we look for it's parent, it must be one of the following:
- `if` (something evaluating to False)
- Function Definition
- Class Definition
- Module (If global code)

If we keep on traversing the ast for the parents in the exactly same order we are bound to encounter one of these and as soon as we do - we should be able to report that particular parent node to be dead.

One catch I can think of right now is that it would give a false positive for code after return statements, but we can sure handle that very specific case.

But again, this theory is completely untested, please give it a harsh review.

**Comment by jendrikseipp** [comment]
If Vulture says that a function is unused, we can check whether this is really the case by checking whether the next line is marked as unused in the coverage.py XML file. The same approach should work for properties, but I don't see a way to check whether classes, variables, attributes are used. Maybe checking functions (and properties) for false-positives is already useful enough.

**Comment by AbdealiJK** [comment]
That would be a good first start - but just being devils advocate when I
say: If Docstrings, comments, etc. are the first line then we should be
careful :)

**Comment by jendrikseipp** [comment]
I don't think that should matter. The only problem I see are functions that are defined on one line, which I'd say we can ignore.

**Comment by jendrikseipp** [comment]
After inspecting the pull request #133, I think we should make the `--make-whitelist` feature more general by splitting it into two parts:

* `--make-whitelist` writes a whitelist to stdout in the following format: `myfunc  # unused function (foo.py:42)`
* `--coverage-xml` lets Vulture ignore functions that are marked as used in the coverage XML report

I think both features are useful on their own and when used in conjunction. Separating them also simplifies the documentation and implementation, I think. 

Rahul, could you please split off one of the features into a separate pull request?

**Comment by RJ722** [comment]
> After inspecting the pull request #133, I think we should make the --make-whitelist feature more general by splitting it into two parts:

I concur - I like this design better. :-)

> `--make-whitelist` writes a whitelist to stdout in the following format: `myfunc # unused function (foo.py:42)`

This format greatly simplifies design. Win-win! \o/ 

I've updated #133 to reflect changes required for `--make-whitelist`. After this gets merged, implementing `--coverage-xml` would become as simple as an if statement.

**Comment by jendrikseipp** [comment]
We came to the conclusion that the `--coverage-xml` feature entails a rather complicated workflow and doesn't add much value now that `--make-whitelist` is implemented.
