### ISSUE TITLE
False unused variable - database models

### ISSUE THREAD

**Issue by AbdealiJK** [jendrikseipp/vulture#110]
If I have a schema (Marshmallow schema), or model (SQLAlchemy model?), all the fields of the model are detected as unused.

Example:
```
class DatedSchema(Schema):
    createdBy = StringField(attribute="created_by", dump_only=True)
    lastModifiedBy = StringField(attribute="last_modified_by", dump_only=True)
    createdDate = fields.DateTime(attribute="created_date", dump_only=True)
    lastModifiedDate = fields.DateTime(attribute="last_modified_date", dump_only=True)
```

These 4 variables are "unused" according to vulture ... but I do need them in my database-table/schema.

Not sure how to ignore these sort of results from vulture.

Note: I do have functions in my schema like `add_role()` or `touch_time()` etc. So, I do not want to exclude the whole file

**Comment by RJ722** [comment]
Hi @AbdealiJK! You can add a whitelist to your project which contains all the variables which are being reported as unused.

For now, your whitelist may contain:
```py
# Whitelist.py
from vulture.whitelist_utils import Whitelist

whitelist_schema = Whitelist()
whitelist_schema.createdBy
whitelist_schema.lastModifiedBy
whitelist_schema.createdDate
whitelist_schema.lastModifiedDate
```

**Comment by AbdealiJK** [comment]
I would need to maintain a very large list here... Typical SQL schema have 40-50 tables for mid-sized projects. Even with 10 columns per table that is 300 variables I need to mention here

**Comment by RJ722** [comment]
I suppose that you would have a file dedicated to schema and/or ORM. If whitelisting is too much overhead, may be just ignore the whole file. Is it feasible?

**Comment by AbdealiJK** [comment]
I actually have a whole folder with these and they do contain a lot of other code other than just the schema info.

For example, I would want to check if I am using the function called `add_role()` in my code or not. The function is in the schema definition as it is modifying the data in my model.

So - yes. I can ignore my entire file. But that is going to ignore more than I want

**Comment by RJ722** [comment]
> I would want to check if I am using the function called add_role() in my code or not. The function is in the schema definition as it is modifying the data in my model.

In that case, the only way we can achieve this with the current infrastructure would be to move the "dynamic" part of your code in the schema to a `utils` module and then excluding the schema only files by using something like:

`vulture . --exclude schema`.

**Comment by jendrikseipp** [comment]
I agree that separating the schemas from the code and excluding the schema files when running Vulture is one option. I think a better solution could be to use the tracer idea from #109.
