### ISSUE TITLE
Document exit codes

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#115]
I guess Vulture exits with following exit codes:

Exit Code | Description
--------- | ------------
`0` | Vulture executes successfully and no dead code is found.
`1` | Vulture executes successfully and dead code is found.
`1` | Vulture could not execute successfully either because the specified file wasn't found or the source was corrupt (Syntax errors, non UTF-8 encoding, contains null bytes)

**Comment by RJ722** [comment]
One more case:

`0` --> show program's version number and exit

**Comment by RJ722** [comment]
@jendrikseipp do you think that we should have different exit codes for different failures?

**Comment by jendrikseipp** [comment]
I don't think we need to document the exit code of `--version`. Also, I don't think we need different exit codes for different failures. If the exit code is not 0, users should investigate, regardless of which exitcode is returned. I think most CI tools only distinguish between 0 and non-zero anyway.

**Comment by RJ722** [comment]
Two more cases:

Exit Code | Description
--------- | ------------
`1` | `--min-confidence` is out of range.
`2` | No input files passed to Vulture or to the `--exclude` flag.

**Comment by jendrikseipp** [comment]
The last two cases should have the same exit code, since they're both command line usage errors. Let's use 2 for both of them, since this is common for usage errors. So in the table we would have an extra line "2 | Invalid command line arguments".

**Comment by RJ722** [comment]
> So in the table we would have an extra line "2 | Invalid command line arguments".

Done!
