### ISSUE TITLE
Test --sort-by-size

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#125]
As discussed in #124, the test for `--sort-by-size` is faulty because it never actually calls the underlying function as no dead code is detected on the first hand.

```py
def test_sort_by_size():
    assert call_vulture(['vulture/', '--sort-by-size']) == 0
```

We'd be needing a completely new kind of test - where we can match the output of vulture to the expected output. This way, we can also test for `verbose` mode.

**Comment by jendrikseipp** [comment]
Let's keep things simple for now and just use

```
def test_sort_by_size():
    assert call_vulture(['vulture/utils.py', '--sort-by-size']) == 1
```

Testing that the items are sorted correctly, should be done in a test that uses the API (maybe tests/test_sorting.py and in a separate PR), not using the script.
