### ISSUE TITLE
Try different tools for code coverage

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#141]
Currently, we are using coveralls for keeping the track of code coverage, but it behaves [strangely sometimes][0]. This can be addressed by inspecting whether other tools (like [codecov][1], etc) give similar results?

[0]: https://github.com/jendrikseipp/vulture/pull/139#discussion_r204216657
[1]: https://codecov.io/

**Comment by jendrikseipp** [comment]
We tried codecov, but liked its output a little less than coveralls. If we ever want to change to codecov, we only need to replace `coveralls` by `codecov` in `.travis.yml`.
