### ISSUE TITLE
make_whitelist is not available as an API

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#143]
Currently, the `make_whitelist` function creates a whitelist and then prints it to stdout, whereas this function might be useful for other linters using Vulture (e.g., https://github.com/coala/coala-bears/issues/2640) and thus should be a part of the public API.

IMHO, we should return a list from the `make_whitelist` method (much like `get_unused_code`) and utilize it in the `report` method when the ``--make_whitelist`` flag is passed.

**Comment by jendrikseipp** [comment]
Could you please paste an example snippet showing how you'd like to use the new API?

**Comment by RJ722** [comment]
I think that `whitelist_message` can be a method of the `Item` class - This would automatically expose it as an API and then would also enable us to use it internally with the report function.

The API might then be used as following:
```python
v = vulture.Vulture()
v.scavenge(filenames)
for item in v.get_unused_code():
     print(item.whitelist_message)
```

**Comment by jendrikseipp** [comment]
Sounds good. Let's call the method `Item.get_whitelist_string()` though.
