### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by walles** [jendrikseipp/vulture#147]
Hi!

Try analyzing this program:
```python
import threading
import logging

logging.basicConfig(level=logging.DEBUG,
                    format='(%(threadName)-10s) %(message)s',
                    )

class MyThread(threading.Thread):
    def run(self):
        logging.debug('running')
        return

for _i in range(5):
    t = MyThread()
    t.daemon = True
    t.start()
```

Current output from `vulture` 0.29:
```
thread.py:11: unused function 'run' (60% confidence)
thread.py:15: unused attribute 'daemon' (60% confidence)
```

Expected output:
Nothing.

The `run()` method is what the thread executes when started: https://docs.python.org/3.7/library/threading.html#threading.Thread.run

The `daemon` attribute is used for telling the thread what flavor it should be: https://docs.python.org/3.7/library/threading.html#threading.Thread.daemon

Is there any way for Vulture to figure these things out by itself so that it doesn't present these false positive warnings?

**Comment by jendrikseipp** [comment]
Yes, I think `run` and `daemon` should be added to a new whitelist for the `threading` module (see `vulture/whitelists`) for examples.
