### ISSUE TITLE
getattr()

### ISSUE THREAD

**Issue by walles** [jendrikseipp/vulture#149]
```python
class Apa(object):
    pass


apa = Apa()
apa.hej = 7
print(getattr(apa, 'hej', 9))
```

Vulture 0.29:
```
getattr.py:6: unused attribute 'hej' (60% confidence)
```

The `hej` value is used through reflection.

In the generic case this could be difficult to support, but in this example where it's a fixed string it should be possible for Vulture to see that `hej` is actually used.

**Comment by RJ722** [comment]
Hey @walles!

Source code for Vulture is mostly written in a way that it doesn't reach out specific cases, but instead generalizes for every possible case. For ignoring `hej` from being reported as unused, you should use a whitelist. :)

**Comment by jendrikseipp** [comment]
I wonder how often `getattr` is used with a fixed string in production code, since in these cases you could just use, e.g., `apa.hej` instead. If this is a common pattern, I think we could add support for the `getattr` function and count `'hej'` as used.

**Comment by The-Compiler** [comment]
I thought the same at first, but here @walles uses the `getattr(object, name, default)` form of `getattr`, which is probably the only valid case of using `getattr` with a fixed string.

Still I expect that to not happen often, because usually you should know what attributes your object has, IMHO.

**Comment by AbdealiJK** [comment]
From what I've seen - getattr is used for cases where you would normally do:

`apa.hej if hasattr(apa, 'hej') else 9`
Or
```
try:
    val = apa.haj
except:
    val = 9
```

**Comment by jendrikseipp** [comment]
I agree. Let's close this then.
