### ISSUE TITLE
Detect dead arguments too

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/vulture#15]
Originally reported by: **Wilfred Hughes (Bitbucket: [Wilfred](https://bitbucket.org/Wilfred), GitHub: [Wilfred](https://github.com/Wilfred))**

----------------------------------------

It would be great if vulture could also detect unused arguments. For example, y is unused here:

```
#!python

def foo(x, y):
    return x + 1
```

----------------------------------------
- Bitbucket: https://bitbucket.org/jendrikseipp/vulture/issue/15

**Comment by lanzz** [comment]
Sorry for bringing a long buried issue back from the dead, but is there any way to _whitelist_ unused function arguments? It is not always possible to rename it with a leading underscore (e.g. when a callback interface passes it as a kwarg).

**Comment by RJ722** [comment]
@lanzz you can create a whitelist file containing a variable with same name as your argument.

For example, for the program [above](https://github.com/jendrikseipp/vulture/issues/15#issue-212050245), the whitelist will look like this:

```python
y
```
