### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by jonapich** [jendrikseipp/vulture#151]
Good morning! :)

I was about to try out the `--ignore-decorators` switch to skip some checks and after a few puzzling attempts I realized it was an unreleased feature! :man_facepalming: 

Was it an oversight? Is there a new release planned soon?

Thank you!

**Comment by jendrikseipp** [comment]
Thanks for nudging me into making a new release :-) Version 1.0 has just been uploaded.

**Comment by RJ722** [comment]
Hey, should we also change the development status from "5: Production/Stable" to "6: Mature"?

**Comment by jendrikseipp** [comment]
I think stage 5 is fine for now :-)
