### ISSUE TITLE
Honour "# noqa: F401" comments

### ISSUE THREAD

**Issue by OddBloke** [jendrikseipp/vulture#160]
Our codebase has to work as far back as Python 3.4, which doesn't have the typing module available. As such, all of our type annotations are in strings (so they are lazily evaluated during type checking and ignored when running normally) and our typing imports are conditional, with "# noqa: F401" appended to silence the flake8 warnings.

vulture doesn't honour these comments, and it seems like an obvious win for it to do so.

(Per http://flake8.pycqa.org/en/2.5.5/warnings.html, F401 is specifically the warning for "`module` imported but unused"; this matches very closely with Vulture's unused import warnings.)

**Comment by OddBloke** [comment]
Looking through existing issues, I've seen that "# noqa" support has generally been rejected. Hopefully this request for just one specific form of noqa comment will be considered, as in my opinion, it would reduce the barrier to adoption substantially.

**Comment by jendrikseipp** [comment]
Since Python 3.4 has reached EOL and Vulture stopped testing for this version recently, I don't think Vulture should add workarounds that are only needed for this version. Your problem seems to be more general though. However, I don't understand why you need imports if all your type annotations are in strings. Could you please provide some example code?

**Comment by anowlcalledjosh** [comment]
Even if type hints are specified as strings, you still have to import the things used in type hints to tell the type checker what they are – it doesn't matter if you say `foo: MyObject` or `foo: "MyObject"` or `foo = None  # type: MyObject`, if mypy doesn't know which `MyObject` you're referring to.

**Comment by jendrikseipp** [comment]
Thanks for the clarification! I agree that honoring F401 noqa comments makes sense. I'd be happy to review a pull request that makes this change.

**Comment by RJ722** [comment]
Regarding honoring `# noqa` comments, I think that once we have Vulture available as a flake-8 plugin (#161), we wouldn't need to develop/maintain this functionality ourselves. Am I thinking in the right direction?

**Comment by The-Compiler** [comment]
@RJ722 I think you're right!

**Comment by jendrikseipp** [comment]
That's true. The question is whether we want to offer this functionality 
to users of standalone Vulture as well. I have no strong opinion on 
this, but I think the decision should depend on the complexity of the 
patch for this functionality and how many users would like to have it.

**Comment by RJ722** [comment]
@OddBloke are you okay with changing all of `# noqa: F401, V104`? (`V104` is issue code Vulture raises for unused imports)

**Comment by jendrikseipp** [comment]
I guess it makes sense to let Vulture honour the F401 code as well.

**Comment by jendrikseipp** [comment]
> I guess it makes sense to let Vulture honour the F401 code as well.

This has been implemented in 5e7fd662ad231105a689085697d72e5536903985.

**Comment by OddBloke** [comment]
Thanks very much!
