### ISSUE TITLE
A canonical example of using vulture for a django project in the docs

### ISSUE THREAD

**Issue by finance-oppoin** [jendrikseipp/vulture#162]
I found this issue https://github.com/jendrikseipp/vulture/issues/109#issuecomment-405044730

and I am not very familiar with vulture and was looking at using it for a django project.

If the documentation can include a simple end-to-end tutorial on using vulture in a hello world version of a Django project, it would be most helpful for newbies like me.

Is that something I can help with?

**Comment by jendrikseipp** [comment]
Maybe you can post the steps you made to use Vulture for Django here and then we can decide whether the info could be useful for others.

**Comment by jendrikseipp** [comment]
Long time without action here. Let me close this issue for now, but feel free to post the Django instructions and I'll reopen it.

**Comment by deronnax** [comment]
@jendrikseipp there isn't much to do, all there is to do is run vulture on the directories you want to check for dead code, like a regular python project.
Exemple of things on which vulture still struggle on for a django project:
All django class fields and `Meta` fields. Those are "descriptive" fields, that don't have to be accessed directly, but describe what the object is made of.

```
➜ cat visits/models.py
from django.db import models
from django.contrib.auth.models import User

class VisitRequest(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    company = models.CharField(max_length=200, blank=True, null=True)
    visit_datetime = models.DateTimeField()

➜ vulture visits/models.py
visits/models.py:5: unused class 'VisitRequest' (60% confidence)
visits/models.py:8: unused variable 'company' (60% confidence)
visits/models.py:10: unused variable 'requester' (60% confidence)
visits/models.py:11: unused variable 'created_at' (60% confidence)
```
