### ISSUE TITLE
false flag on overridden methods

### ISSUE THREAD

**Issue by Bergiu** [jendrikseipp/vulture#163]
If I override a function from a base class and don't use all parameters, the parameters not used in the overridden method are shown as "unused variable"

Example (from a file called gmb/database/schema.py lines 10 to 12):
```py
class AutoInt(Enum):
    def _generate_next_value_(name, start, count, last_values):
        return count
```

The function is defined in the Enum class and overridden here, but this errors occur:

```
gmb/database/schema.py:11: unused variable 'last_values' (100% confidence)
gmb/database/schema.py:11: unused variable 'name' (100% confidence)
gmb/database/schema.py:11: unused variable 'start' (100% confidence)
```

**Comment by jendrikseipp** [comment]
I think the warning is correct, since the variables are really unused. The Pythonic solution would be to use "_" as variable name for the three unused variables.

**Comment by Bergiu** [comment]
Thanks

**Comment by yurikhan** [comment]
No, renaming arguments is not a solution. Clients of the base class expect to be able to call the method with keyword arguments. Consider:

```python
class Foo:
    def bar(self, x: int, y: str) -> None:
        return '{} {}'.format(x, y)

def foo_client(foo: Foo) -> None:
    foo.bar(x=42, y='Hello World')

foo_client(Foo())  # '42 Hello World'


class Baz(Foo):
    def bar(self, x: int, _y: str) -> None:
        return '*' * x

foo_client(Baz())  # boom!
```

Most libraries out there document their method argument names and types, and very few actually say whether they are positional-only and thus safe to rename when overriding.

The only viable workaround I’ve found is this:

```python
class Baz(Foo):
    def bar(self, x: int, y: str) -> None:
        _ = y
        return '*' * x
```

**Comment by jendrikseipp** [comment]
Thanks for the example! In this case, I recommend using a whitelist file containing the name `y` (optionally plus a comment that explains where y occurs in the code).

**Comment by yurikhan** [comment]
How would such a whitelist look or work? Doesn’t it have to actually refer to the entity that is detected as unused?

**Comment by RJ722** [comment]
@yurikhan Whitelists latch onto the fact that Vulture doesn't support namespaces. Once a variable is referenced anywhere in the project, it is deemed as used. Due to the same, the case you mentioned here won't report any output at all.
