### ISSUE TITLE
Tests fails with py3.8

### ISSUE THREAD

**Issue by karelyatin** [jendrikseipp/vulture#166]
Unit tests failing with py3.8, On Fedora system tested with tox -py38, Need adoption of vulture code to py3.8.

[vulture]$ tox -epy38
GLOB sdist-make: /tmp/vulture/setup.py
py38 inst-nodeps: /tmp/vulture/.tox/dist/vulture-0.27.zip
py38 installed: atomicwrites==1.3.0,attrs==19.1.0,coverage==4.5.3,importlib-metadata==0.18,more-itertools==7.2.0,packaging==19.0,pluggy==0.12.0,py==1.8.0,pyparsing==2.4.1,pytest==5.0.1,pytest-cov==2.7.1,six==1.12.0,vulture==0.27,wcwidth==0.1.7,zipp==0.5.2
py38 run-test-pre: PYTHONHASHSEED='424332550'
py38 runtests: commands[0] | py.test
============================================================== test session starts ===============================================================
platform linux -- Python 3.8.0b2, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
cachedir: .tox/py38/.pytest_cache
rootdir: /tmp/vulture, inifile: setup.cfg
plugins: cov-2.7.1
collected 144 items                                                                                                                              

tests/test_conditions.py ..............                                                                                                    [  9%]
tests/test_confidence.py ......                                                                                                            [ 13%]
tests/test_errors.py ...                                                                                                                   [ 15%]
tests/test_format_strings.py FFFFF.                                                                                                        [ 20%]
tests/test_imports.py .............                                                                                                        [ 29%]
tests/test_item.py .                                                                                                                       [ 29%]
tests/test_scavenging.py .......................................                                                                           [ 56%]
tests/test_script.py .........                                                                                                             [ 63%]
tests/test_size.py ..F........................                                                                                             [ 81%]
tests/test_sorting.py .                                                                                                                    [ 82%]
tests/test_unreachable.py .........................                                                                                        [100%]

==================================================================== FAILURES ====================================================================
_____________________________________________________________ test_old_format_string _____________________________________________________________

v = <vulture.core.Vulture object at 0x7f5c3e3643a0>

    def test_old_format_string(v):
        v.scan("'%(a)s, %(b)d' % locals()")
>       check(v.used_names, ['a', 'b', 'locals'])

tests/test_format_strings.py:7: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

items_or_names = LoggingSet({'locals'}), expected_names = ['a', 'b', 'locals']

    def check(items_or_names, expected_names):
        if isinstance(items_or_names, set):
            # items_or_names is a set of strings.
>           assert items_or_names == set(expected_names)
E           AssertionError

tests/__init__.py:10: AssertionError
-------------------------------------------------------------- Captured stdout call 
_____________________________________________________________ test_new_format_string _____________________________________________________________

v = <vulture.core.Vulture object at 0x7f5c3e3d2a30>

    def test_new_format_string(v):
        v.scan("'{a}, {b:0d} {c:<30} {d:.2%}'.format(**locals())")
>       check(v.used_names, ['a', 'b', 'c', 'd', 'locals'])

tests/test_format_strings.py:12: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

items_or_names = LoggingSet({'locals'}), expected_names = ['a', 'b', 'c', 'd', 'locals']

    def check(items_or_names, expected_names):
        if isinstance(items_or_names, set):
            # items_or_names is a set of strings.
>           assert items_or_names == set(expected_names)
E           AssertionError

tests/__init__.py:10: AssertionError
-------------------------------------------------------------- Captured stdout call 
_________________________________________________________ test_new_format_string_access __________________________________________________________

v = <vulture.core.Vulture object at 0x7f5c3e3645b0>

    def test_new_format_string_access(v):
        v.scan("'{a.b}, {c.d.e} {f[g]} {h[i][j]}'.format(**locals())")
>       check(v.used_names, ['a', 'c', 'f', 'h', 'locals'])

tests/test_format_strings.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

items_or_names = LoggingSet({'locals'}), expected_names = ['a', 'c', 'f', 'h', 'locals']

    def check(items_or_names, expected_names):
        if isinstance(items_or_names, set):
            # items_or_names is a set of strings.
>           assert items_or_names == set(expected_names)
E           AssertionError

tests/__init__.py:10: AssertionError
-------------------------------------------------------------- Captured stdout call 
_______________________________________________________ test_new_format_string_attributes ________________________________________________________

v = <vulture.core.Vulture object at 0x7f5c3e3d20a0>

    def test_new_format_string_attributes(v):
        v.scan("'{a.b}, {c.d.e} {f[g]} {h[i][j].k}'.format(**locals())")
>       check(v.used_names, ['a', 'c', 'f', 'h', 'locals'])

tests/test_format_strings.py:22: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

items_or_names = LoggingSet({'locals'}), expected_names = ['a', 'c', 'f', 'h', 'locals']

    def check(items_or_names, expected_names):
        if isinstance(items_or_names, set):
            # items_or_names is a set of strings.
>           assert items_or_names == set(expected_names)
E           AssertionError

tests/__init__.py:10: AssertionError
-------------------------------------------------------------- Captured stdout call 
_________________________________________________________ test_new_format_string_numbers _________________________________________________________

v = <vulture.core.Vulture object at 0x7f5c3e412490>

    def test_new_format_string_numbers(v):
        v.scan("'{0.b}, {0.d.e} {0[1]} {0[1][1].k}'.format('foo')")
        check(v.used_names, [])
>       check(v.used_attrs, ['b', 'd', 'e', 'k', 'format'])

tests/test_format_strings.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

items_or_names = LoggingSet({'format'}), expected_names = ['b', 'd', 'e', 'k', 'format']

    def check(items_or_names, expected_names):
        if isinstance(items_or_names, set):
            # items_or_names is a set of strings.
>           assert items_or_names == set(expected_names)
E           AssertionError

tests/__init__.py:10: AssertionError
-------------------------------------------------------------- Captured stdout call 
1 Constant(value='foo', kind=None) '{0.b}, {0.d.e} {0[1]} {0[1][1].k}'.format('foo')
_______________________________________________________________ test_size_if_else ________________________________________________________________

    def test_size_if_else():
        example = """
    @identity
    class Foo(object):
        @identity
        @identity
        def bar(self):
            if "a" == "b":
                pass
            elif "b" == "c":
                pass
            else:
                pass
    """
>       check_size(example, 11)

tests/test_size.py:81: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

example = '\n@identity\nclass Foo(object):\n    @identity\n    @identity\n    def bar(self):\n        if "a" == "b":\n            pass\n        elif "b" == "c":\n            pass\n        else:\n            pass\n'
size = 11

    def check_size(example, size):
        tree = ast.parse(example)
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and node.name == 'Foo':
>               assert count_lines(node) == size
E               assert 10 == 11
E                +  where 10 = count_lines(<_ast.ClassDef object at 0x7f5c3e2ece20>)

tests/test_size.py:36: AssertionError

----------- coverage: platform linux, python 3.8.0-beta-2 ------------
Name                                    Stmts   Miss  Cover
-----------------------------------------------------------
vulture/__init__.py                         3      0   100%
vulture/__main__.py                         2      0   100%
vulture/core.py                           287      1    99%
vulture/lines.py                           28      0   100%
vulture/utils.py                           74      2    97%
vulture/whitelists/argparse.py              6      0   100%
vulture/whitelists/ast.py                  67      0   100%
vulture/whitelists/collections.py           3      0   100%
vulture/whitelists/sys.py                   5      0   100%
vulture/whitelists/unittest.py             13      0   100%
vulture/whitelists/whitelist_utils.py       4      0   100%
-----------------------------------------------------------
TOTAL                                     492      3    99%
Coverage HTML written to dir htmlcov

====================================================== 6 failed, 138 passed in 2.47 seconds ======================================================
ERROR: InvocationError for command '/tmp/vulture/.tox/py38/bin/py.test' (exited with code 1)
____________________________________________________________________ summary _____________________________________________________________________
ERROR:   py38: commands failed

Background: detected while packaging in Fedora, there are some changes to ast module in python3.8:- https://bugzilla.redhat.com/show_bug.cgi?id=1716536

**Comment by RJ722** [comment]
Hello @karelyatin,

Thanks for reporting this. I will take a look. @jendrikseipp can you please assign this issue to me?

Sorry for getting back on this so late. I missed the notification email.

**Comment by jendrikseipp** [comment]
@RJ722 Great to hear, I assigned you to this.

**Comment by jendrikseipp** [comment]
I went ahead and fixed the tests for Python 3.8. @karelyatin For me only 3 tests failed under Python 3.8 beta 4. Feel free to reopen if there are more tests failing for you under this Python version or any later Python 3.8 version.
