### ISSUE TITLE
"encoding declaration in Unicode string" with BOM

### ISSUE THREAD

**Issue by dandersoninc** [jendrikseipp/vulture#170]
Vulture reports ""encoding declaration in Unicode string"" for UTF files saved with a Byte Order Mark with or without the presence of a coding: string in the file.  The workaround is to not save files with BOM, but that plays havok on my git history!

**Comment by jendrikseipp** [comment]
Thanks for the report! Which OS and which Python version are you using? Could you please post an example file with a BOM?

**Comment by dandersoninc** [comment]
It was Python 2.7.15 on Windows 10.  Works for any BOM UTF8 file, ie with first 3 bytes as:
byte1 == '\xef'
byte2 == '\xbb'
byte3 == '\xbf'
[bomtest.zip](https://github.com/jendrikseipp/vulture/files/3564975/bomtest.zip)

**Comment by dandersoninc** [comment]
Thanks for the quick fix!
