### ISSUE TITLE
Mark imports in `__all__` as used

### ISSUE THREAD

**Issue by Zac-HD** [jendrikseipp/vulture#172]
I've been experimenting with Vulture on [Hypothesis](https://github.com/HypothesisWorks/hypothesis/tree/master/hypothesis-python/src/hypothesis) - which has found an unused argument I'd like to fix, so thanks! - and noticed that *some* of the imports to [this module](https://github.com/HypothesisWorks/hypothesis/blob/master/hypothesis-python/src/hypothesis/strategies.py) are flagged as unused with 90% confidence.

Of course, the whole point of that module is just to make things publicly available, and we verify that at runtime at the bottom of the module.  Only four names make it into the Vulture output, so I assume that `__all__` is supposed to be taken into account and it's just failing here for some reason?

**Comment by jendrikseipp** [comment]
So far, we don't take `__all__` into account, but I think this feature should be added. I'll leave this issue open to address that. Pull requests welcome :-)

In your case, it seems some of your imports are not mentioned in other parts of the analyzed code.

**Comment by jendrikseipp** [comment]
@kreathon fixed this in #282.
