### ISSUE TITLE
How to ignore `if False:` import blocks?

### ISSUE THREAD

**Issue by Zac-HD** [jendrikseipp/vulture#173]
For Hypothesis, we have `typing` module imports hidden behind a literal `if False:` at the module level.  It would be more idiomatic to use `if typing.TYPE_CHECKING:`, but of course we can't import that on Python 2 either or the problem would go away :wink: 

So is there a way to whitelist this condition without having to list out every different combination of imports we might need?  Or take this as a proposal to skip literal module-level `if False:` clauses because they're not at all subtle!

**Comment by jendrikseipp** [comment]
We're planning to honour "# noqa: F401" comments for "unused" imports, see #160. I think this would cover your use case. If you don't want to wait, of course you can just use a whitelist Python file that lists all typing module types.
