### ISSUE TITLE
visit_Str is deprecated in Python3.8

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#175]
According to https://docs.python.org/3/library/ast.html:

> Deprecated since version 3.8: Methods visit_Num(), visit_Str(), visit_Bytes(), visit_NameConstant() and visit_Ellipsis() are deprecated now and will not be called in future Python versions. Add the visit_Constant() method to handle all constant nodes.

Of all of these, we are only using the `visit_Str` function.

**Comment by jendrikseipp** [comment]
Interesting! It seems ast.Constant was introduced in Python 3.6. I think we should add a visit_Constant() method alongside visit_Str() to be future-proof.
