### ISSUE TITLE
Add test cases for f-strings

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#177]
Hi @jendrikseipp,

During PyCon India 2019 devsprints, I was working on the TODO:

> Scan f-strings under Python 3.8+.

But, it turns out that the f-strings are automatically scanned because

Turns out that they are parsed as a `JoinedStr` ast node, which then has a child `FormattedValue` - which will contain references to `Name`, `Str`, operation nodes, etc. Since we already have methods to visit these nodes in place, we're already handling f-strings perfectly.

Am I missing something crucial?

**Comment by RJ722** [comment]
The only case which didn't work currently was the case of detecting unreachable code in conditional expressions, much like the following:

```python
print(f'My name: {"RJ722" if True else "Rahul"}')
```

But, I could later trace it to the fact that the conditional expressions are being parsed as `IfExp` nodes (which we don't visit) rather than the usual `If` nodes, and thus it's a more broader issue in it's own (will raise another issue if you concur).

**Comment by jendrikseipp** [comment]
Thanks for investigating! I think we should add tests for f-strings in 
any case.

And yes, I do concur regarding the IfExp nodes.
