### ISSUE TITLE
"Unreachable code after _name_" entries cannot be used in whitelist

### ISSUE THREAD

**Issue by HitLuca** [jendrikseipp/vulture#190]
After running vulture in order to generate a whitelist with

`vulture my_module --make-whitelist > whitelist.py`

I noticed that a class of entries cannot silence the script's output (`vulture my_module whitelist.py`), specifically the unreachable code ones.

`# unreachable code after '_name_' (my_module/.../name.py:###)`

I didn't find a way to reliably suppress such outputs when running vulture, I tried to remove the comment `#`, but that breaks the whitelist parsing.

Not that it matters too much for me, I only have 3 entries of that sort, but for large projects it could be a bigger issue.

**Comment by jendrikseipp** [comment]
Thanks for the report! Unfortunately, there is no way to silence such errors at the moment. The assumption is that unreachable code should normally be easy to be removed. Is that different in your code? Can you give an example of where this happens?

**Comment by HitLuca** [comment]
My use case is of a coworker that is adding some functionality but at the moment it's not fully completed. For that reason he returns early or raises an exception, but after it there's code that needs to be there for a future feature. Whether is bad practice or not I believe there should be an option to stop such warnings

**Comment by jendrikseipp** [comment]
We'd like to honor `# noqa` comments eventually, but so far no one has made a pull request. See also #160.

**Comment by RJ722** [comment]
I think we can close this.

**Comment by jendrikseipp** [comment]
Yes, that's right.
