### ISSUE TITLE
support 3.5 async/await

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/vulture#20]
Originally reported by: **Anonymous**

----------------------------------------

It depends on the runtime, but support for async/await can be easily added (just point from visit_AsyncFunctionDef to visit_FunctionDef)

----------------------------------------
- Bitbucket: https://bitbucket.org/jendrikseipp/vulture/issue/20

**Comment by jack17529** [comment]
@jendrikseipp sounds great I am applying to work on this project in coala organization can you please guide me

**Comment by jendrikseipp** [comment]
Sounds good! For this issue, you'll have to point from visit_AsyncFunctionDef to visit_FunctionDef and add a test case to `test_scavenging.py` that tests the new language constructs. You'll have to make sure that the test only gets executed under the Python versions that support the language feature.

**Comment by jack17529** [comment]
@jendrikseipp I am on it sir.

**Comment by jack17529** [comment]
@jendrikseipp  Sir can you please join https://gitter.im/coala/coala/gsoc and other gitter rooms  or if you don't like please send me your email id , either way you want to communicate as I am currently reading the code of vulture repo.

**Comment by jendrikseipp** [comment]
The best way to reach me is via email. I added my address to my profile 
page https://github.com/jendrikseipp.

**Comment by jack17529** [comment]
import sys
 if (sys.version_info > (3, 0)):
     # Python 3 code in this block
     import base64
     return base64.b64encode(data).decode()
 else:
     # Python 2 code in this block
     return data.encode("base64")

as according to Python documentation we can use sys.version_info:
A tuple containing the five components of the version number: major, minor, micro, releaselevel, and serial. All values except releaselevel are integers; the release level is 'alpha', 'beta', 'candidate', or 'final'. The version_info value corresponding to the Python version 2.0 is (2, 0, 0, 'final', 0). The components can also be accessed by name, so sys.version_info[0] is equivalent to sys.version_info.major and so on.

**Comment by jack17529** [comment]
@jendrikseipp 
Should I use this in def visit_FunctionDef(self, node) to make it sync with test_scavenging.py
Or should I make a new function that first checks the version and then only executes vulture.py

**Comment by jendrikseipp** [comment]
In vulture.py we shouldn't need to add an additional test for Python 3 since `visit_AsyncFunctionDef` will only be called in Python versions that support it. However, you need to skip the test that tests the new feature on older interpreters with the skipif py.test feature: https://docs.pytest.org/en/latest/skipping.html#id1.

**Comment by jack17529** [comment]
import sys
@pytest.mark.skipif(sys.version_info < (3,0),
                    reason="requires python3.0")
def test_function4(v):
	v.scan("""\
class Bar(object):
    def foo(self):
        pass

b = Bar()
b.foo
 """)	
	assert v.used_attrs == ['foo']
    assert v.unused_funcs == []
	assert v.defined_props == []
    assert v.defined_funcs == ['Bar', 'foo']

Is this right please check.

**Comment by jendrikseipp** [comment]
It would be easier to comment on a pull request.

- `async def` was introduced in Python 3.5, not 3.0.
- Obviously, the test should use `async def`.
