### ISSUE TITLE
Calling parent class __init__ in PY2 style was hidden

### ISSUE THREAD

**Issue by milton0825** [jendrikseipp/vulture#203]
We found that if a class that calls its parent class `__init__` method using the old PY2 syntax. That class is classified as used even though it is not used elsewhere.

```
class AthenaOperator(BaseOperator):

    def __init__(self,
                 sql,  # type: str
                 *args,  # type: List[Any]
                 **kwargs  # type: Dict[Any, Any]
                 ):
        super(AthenaOperator, self).__init__(*args, **kwargs)
```

**Comment by jendrikseipp** [comment]
Thanks for reporting this. Given that the old syntax will gradually fade out, we are not planning to adapt Vulture for this.
