### ISSUE TITLE
Stop reporting unused `cls` variable in class methods

### ISSUE THREAD

**Issue by pquentin** [jendrikseipp/vulture#204]
vulture correctly ignores an unused `self` variable in a method, but fails to ignore `cls` in class methods.

## Steps to reproduce

```
class MyClass:
    @classmethod
    def my_class_method(cls):
        print("not using cls")


MyClass.my_class_method()
```

## Actual output

```
t.py:3: unused variable 'cls' (100% confidence)
```

## Expected output

Nothing, like for `self`.

Thanks!

**Comment by jendrikseipp** [comment]
Thanks for the report! I can see that reporting `cls` might lead to many false or at least "unwanted" positives. However, here, Vulture shows that the method could actually be a staticmethod instead of a classmethod. I think this might actually be useful, do you agree?

**Comment by pquentin** [comment]
Oh, yes, that makes complete sense, thanks. We'll switch to static methods.
