### ISSUE TITLE
`#noqa` does not ignore `unsatisfiable 'if' condition`

### ISSUE THREAD

**Issue by CristhianMotoche** [jendrikseipp/vulture#206]
Hi!

I added a conditional that won't be executed because I only wrote it to get a reference to a type for a function. This is a trick that the [`mypy`](https://github.com/python/mypy/issues/1597#issuecomment-222795658) community suggest to avoid circular dependencies.

However, I got an `unsatisfiable 'if' condition (100% confidence)` error, which makes sense. So, I added `noqa` expecting to ignore it, but it didn't.

Minimum code to reproduce:

```py
# ex.py
if False:  # noqa
    from foo import Foo


def createFoo(foo: Foo) -> Foo:
    return Foo()

# foo.py
class Foo:
    pass
```

Vulture results:
```
$ vulture ex.py
ex.py:1: unsatisfiable 'if' condition (100% confidence)
...
```

**Comment by jendrikseipp** [comment]
The noqa functionality has not been released yet. Sorry for the confusion! See https://github.com/jendrikseipp/vulture/issues/205#issuecomment-627168622

**Comment by CristhianMotoche** [comment]
Thanks for the clarification. @jendrikseipp
