### ISSUE TITLE
Whitelist defaultdict.default_factory

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/vulture#21]
Originally reported by: **bitserver (Bitbucket: [bitserver](https://bitbucket.org/bitserver), GitHub: [bitserver](https://github.com/bitserver))**

----------------------------------------

I have a collections.defaultdict(). After I have finished populating it, I have to set its default_factory attribute to None. vulture then tells me that default_factory is an unused attribute, but I can't help it, as that's how defaultdict works.

----------------------------------------
- Bitbucket: https://bitbucket.org/jendrikseipp/vulture/issue/21

**Comment by RJ722** [comment]
Hi @jendrikseipp!
I am new to vulture and would like to work on vulture, can you please guide me through how to configure development environment and what would be the workflow involved?

Also, I would like to solve this bug. Can I send a PR?

**Comment by jendrikseipp** [comment]
To sum up the status of this issue: We want to create a `whitelist_python.py` file similar to the existing `whitelist.py` file. For now, it should contain 

```
import collections
collections.defaultdict(list).default_factory
```

(Note to myself: default_factory can't be passed to defaultdict() as a keyword argument.)

Vulture doesn't need any special development setup, as far as I can tell. The workflow is that you clone the repo, create a new branch "python-whitelist" and add the new file `whitelist_python.py` to the top-level directory. Then you can make a pull request.

**Comment by jack17529** [comment]
@jendrikseipp , but this was a proposal issue?

Can we solve proposal issues right now ?

**Comment by RJ722** [comment]
Hi! @jack17529 
Proposal issues don't mean - solve them as a part of GSoC proposal, they are just changes which are proposed and can apparently be solved any time! 

Hope so, I have cleared the confusion! :smile:

**Comment by jack17529** [comment]
Okay then I can solve all of them right now that seems lot of work thanx man @RJ722

**Comment by jendrikseipp** [comment]
To clarify: this issue is not part of any "proposal". You can solve issues any time you want :-)
