### ISSUE TITLE
API

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/vulture#23]
Originally reported by: **Lasse Schuirmann (Bitbucket: [sils1297](https://bitbucket.org/sils1297), GitHub: [sils1297](https://github.com/sils1297))**

----------------------------------------

Would be nice to have a way to use vulture programmatically, like:

```
from vulture import find_unused_code

find_unused_code(
    files={'test_1': 'def test(): pass', 'test_2': 'def test2: pass\nfrom test_1 import test\ntest()'}
    )
```

We use vulture in coala (coala.io) and that'd make things way more efficient etc. (in memory file passing, we have them already read e.g.)

----------------------------------------
- Bitbucket: https://bitbucket.org/jendrikseipp/vulture/issue/23

**Comment by jendrikseipp** [comment]
I think a first step for this issue could be to implement the `find_unused_code` function as specified above with the functions available in vulture at the moment, i.e., `Vulture.scan()`, `Vulture.report()` or `Vulture.unused_funcs()`, etc. Once we know what is missing, we can see how to implement it.

**Comment by RJ722** [comment]
Would it be suitable, if it returns something similar to: ([referred code](https://github.com/jendrikseipp/vulture/blob/master/vulture.py#L193-L194))
```python
print("%s:%d: Unused %s '%s'" % (
    format_path(item.filename), item.lineno, item.typ, item))
```
Would a list of all such tuples like 
```python
[(item1.filename, item1.lineno, item1.typ, item1), (item2.filename, item2.lineno, item2.typ, item2)...]
```
be feasible?

**Comment by jendrikseipp** [comment]
If it turns out to be useful, we could add a method `Vulture.get_unused_items()` that returns a sorted list of unused Item objects. The filename, lineno and typ attributes can be used to inspect items.

**Comment by jack17529** [comment]
If no one is working then can I please work on this issue.

**Comment by jendrikseipp** [comment]
We are already working on this, sorry.

**Comment by jendrikseipp** [comment]
During our work on https://github.com/coala/coala-bears/pull/1814 we noticed that the existing API already provides all relevant info.
