### ISSUE TITLE
Add a summary after running the command

### ISSUE THREAD

**Issue by jonathan-s** [jendrikseipp/vulture#238]
It would be useful with a summary. Two statistics that comes to mind are.
- How many places are affected by dead code. 
- How many lines in total are considered dead code. 
- Optionally, average confidence of all the dead code.

**Comment by jendrikseipp** [comment]
I agree that these statistics are interesting, but I wouldn't bake them into Vulture. Instead, you can use `vulture *.py | wc -l` to count the places with dead code.

**Comment by jonathan-s** [comment]
Yeah, `wc -l` works for counting the number of lines. Do you also have a neat of way of collecting the number of lines each place is responsible for? 

Ie sum the value where `135` is located. That seems a lot trickier. 
```
apps/februus/handlers/gnip.py:19: unused class 'GnipHandler' (60% confidence, 135 lines)
```

**Comment by jendrikseipp** [comment]
For that, I recommend using a suitable `awk` script (I'm not versed in that, but a stackoverflow search will help you there).
