### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by sweetgiorni** [jendrikseipp/vulture#240]
I made this VS Code extension for personal use. It's not yet fully functional in terms of configuration but it works enough. If you want it feel free to fork, or I can give ownership of the repo + VS Code marketplace extension, I don't really care. I can also hang on to it, but I make no guarantees about quality or maintenance timelines :)

https://github.com/sweetgiorni/vulture-vscode
https://marketplace.visualstudio.com/items?itemName=AlexSweet.vulture-vscode

![image](https://user-images.githubusercontent.com/12527888/98460642-0126e980-215b-11eb-8bd2-67a39f4d938e.png)

**Comment by jendrikseipp** [comment]
That's great! Thanks for your work on this! I'm happy for you to maintain the extension with the timeline that works for you.

**Comment by sweetgiorni** [comment]
Okie doke, one more weekend project for me! Once it's whipped into shape I'll send a PR to link to it from your README. I may also open some feature request tickets that would enhance the functionality of the extension, like enhanced output so individual tokens can be highlighted instead of entire lines, etc.

**Comment by jendrikseipp** [comment]
Sounds great!
