### ISSUE TITLE
Auto ignore classes that have the unittest.TestCase base class

### ISSUE THREAD

**Issue by davidhart82** [jendrikseipp/vulture#242]
We tend to store unittests in the same script that we're testing, so the current auto ignoring of tests that live in a test/tests directory is not suitable for us.

It would seem, rather than guessing that tests are always in a test/tests directory (or indeed that non-tests wouldn't be stored in such a directory), that it would be useful to check the base class?

**Comment by jendrikseipp** [comment]
Unfortuntately, checking the base class (or the class ancestry) would make the code much more involved. Therefore, this is currently not a goal.
