### ISSUE TITLE
Option to restrict `unused` types to consider

### ISSUE THREAD

**Issue by deathiop** [jendrikseipp/vulture#243]
Hello,

Would you accept the idea of having a configuration entry / command line flag that allows one to specify 

> I only want to find unused classes and functions, I don't care about the unused variables and other stuff

?

Something like `vulture --unused-classes --unused-variables mydir` (though I don't mind any other format).

**Comment by jendrikseipp** [comment]
I think the best solution for this is to use `vulture ... | grep 'unused class\|unused variable'` to obtain the results you want to see.

**Comment by deathiop** [comment]
I do agree I can filter the output. Though, the way I see it is that vulture might skip computing the parts the user is not interested in, hence making it faster than an output filter.
