### ISSUE TITLE
Fix tuple-arg parsing in vulture 1.6

### ISSUE THREAD

**Issue by csilvers** [jendrikseipp/vulture#250]
I am using vulture 1.6 on my python2 repository.  It errored out while running, due to some weird ways we define arguments in some of our functions, which I fixed at https://github.com/Khan/vulture/commit/9a34fb4e43a0d5385ea91dab5e2db6a201e865ef.

However, I did not make a pull request because I don't know if any new releases are being made in the vulture 1 series.  (Or even how to make a pull request for such a thing!)  Please feel free to do with the fix-commit whatever you see fit!

**Comment by jendrikseipp** [comment]
Thanks for reaching out! I think backporting fixes for unsupported Python versions is too much work though.
