### ISSUE TITLE
Should add support for pycharm / jetbrain statements.

### ISSUE THREAD

**Issue by jimmy927** [jendrikseipp/vulture#251]
Example:

```
# noinspection PyUnusedLocal
def terminate_process(signal_number, frame):
    print("signal Received: %s", signal.Signals(signal_number).name)
    raise SystemExit
```

**Comment by RJ722** [comment]
@jimmy927 Can you elaborate some more on this -- What is the outcome you want to achieve? How are you using Vulture with PyCharm/JetBrains? And how is the code snipped above relevant to it?

**Comment by jendrikseipp** [comment]
I think in this case it's cleaner to add `del frame` at the top of the function to let Vulture ignore the unused variable (see Vulture README.md file).
