### ISSUE TITLE
Filtering out calls to a deadcode from individual directories

### ISSUE THREAD

**Issue by karolpawlowski** [jendrikseipp/vulture#252]
Hi,

is there a way in vulture to mark code as dead even if it is called from directories that aren't "production" code, eg. unit tests?

Regards
Karol

**Comment by RJ722** [comment]
Hey, Karol! not sure what you mean here: do you want to mark used code as dead here? or are you looking for ways to ignore test directories?

**Comment by karolpawlowski** [comment]
Ignore test directories, to not count calls to some methods from test
directories.

niedz., 28 lut 2021 o 11:32 Rahul Jha <notifications@github.com> napisał(a):

**Comment by RJ722** [comment]
You can use the exclude parameter, `--exclude tests/`

**Comment by jendrikseipp** [comment]
Thanks, @RJ722 for handling this!
