### ISSUE TITLE
False positive on unused attribute

### ISSUE THREAD

**Issue by bje-** [jendrikseipp/vulture#257]
Packages like `pint` use attributes to control behaviour. Here is a very simple example:

```
import pint
ureg = pint.UnitRegistry()
ureg.default_format = '.2f~P'
```

Vulture reports that the attribute is unused:

```
foo.py:3: unused attribute 'default_format' (60% confidence)
```

**Comment by jendrikseipp** [comment]
That sounds like a good fit for a pint whitelist:

```
import pint
ureg = pint.UnitRegistry()
ureg.default_format
```

If you pass this file to Vulture in addition to your normal files, Vulture will not complain.

If you like, you could prepare a pull request for this by putting the code into a file called vuture/whitelists/pint.py

**Comment by bje-** [comment]
Thanks, will do.
