### ISSUE TITLE
Obvious unused functions are not reported with 70% min confidence

### ISSUE THREAD

**Issue by noorul** [jendrikseipp/vulture#261]
Reproduction recipe (test.py):

```python
def foo():
    pass


def bar():
    pass


bar()
```

Vulture output:

```log
% ./ENV/bin/vulture --min-confidence=60 test.py
test.py:1: unused function 'foo' (60% confidence)
% ./ENV/bin/vulture --min-confidence=70 test.py
% 
```

**Comment by RJ722** [comment]
This is how it meant to be -- when the `min-confidence` flag is supplied, only results with confidence greater than the supplied value are shown. 

It'd be nice to know what you expected to happen here?

**Comment by noorul** [comment]
For the snippet I was expecting vulture to report this unused function  with 100%. Am I missing something?

**Comment by RJ722** [comment]
Ah, I see. The confidence value is based on the 'type' of the unused item. For functions/methods, it is always 60%. For unused imports, it's 95%, and so on.

**Comment by noorul** [comment]
Then I am not sure whether I understood it properly. I set vulture to use a 70% confidence level because lower than that was giving false positive outputs. But this completely filtered out functions and methods.

**Comment by RJ722** [comment]
In that case, to deal with false positives, I'd recommend adding a whitelist. You can even run Vulture with the  `--make-whitelist` flag -- this would print all the results in a form directly usable as a whitelist. More info in the README.

**Comment by noorul** [comment]
I managed to move to a 60% confidence level. I see that --make-whitelist is an option.
