### ISSUE TITLE
Dataclass variables are tagged as unused variables

### ISSUE THREAD

**Issue by jmmcclaineng** [jendrikseipp/vulture#264]
We have a dataclass like the below we are using for data representation and vulture seems to treat these as unused variables.

Example dataclass:

```
@dataclass
class DHCPV6Response:
    total: int = 0
    solicit: int = 0
    advertise: int = 0
    request: int = 0
    confirm: int = 0
    renew: int = 0
    rebind: int = 0
    reply: int = 0
    release: int = 0
    decline: int = 0
    reconfigure: int = 0
    information_request: int = 0
    relay_forw: int = 0
    relay_reply: int = 0
    discards: int = 0

```
Example unused variables:
```
advertise  # unused variable (adtn_1u_olt/inspect/interface/virtual/modeled_inspect/subscriber/dhcpv6_response.py:17)
confirm  # unused variable (adtn_1u_olt/inspect/interface/virtual/modeled_inspect/subscriber/dhcpv6_response.py:19)
renew  # unused variable (adtn_1u_olt/inspect/interface/virtual/modeled_inspect/subscriber/dhcpv6_response.py:20)

```

**Comment by volans-** [comment]
This is happening to me too. In my case the variables are used only in a `format()` call using `self`. So something like:

```python
SOME_TEMPLATE = """...{s.foo}...{s.bar}..."""

@dataclass
class MyDataclass:

    foo: str
    bar: str

    def __str__(self):
        return SOME_TEMPLATE.format(s=self)
```

**Comment by hughhan1** [comment]
I also have this same issue. Is it possible to add something similar to the list of ignored decorators, like a list of superclasses such that all subclasses extending those superclasses should be ignored by vulture?

**Comment by jendrikseipp** [comment]
I think the best solution for these types of situations is to use a whitelist module such as the following:

```
# mywhitelist.py
from myfile import MyDataclass
MyDataclass.foo
MyDataclass.bar
```

Then add this module to the list of paths that Vulture scans. You may also want to call `python mywhitelist.py` in your CI tests to check that all whitelisted items still exist in the code base.

**Comment by Apakottur** [comment]
The whitelist approach works, but I think that having a `--ignore-classes` option would be really nice, for dataclasses, pydantic models, named tuples and other dataclass-like classes.

**Comment by jendrikseipp** [comment]
Why would dataclass-like classes benefit more from a `--ignore-classes` option than regular classes? In both cases the member variables can be used explicitly or only implicitly. Am I missing something?

**Comment by Apakottur** [comment]
At least in my use case, dataclasses (and pydantic `BaseModel`) are often used to declare the attributes of a JSON object coming from an external API.
Usually I construct the dataclass attributes (based on a JSON blob, or an API documentation) and then use some/all of them for my logic.
Often I am not using all of them in the final result, but I want to keep the whole list of attributes for future reference and to avoid having to parse the JSON blob again.

In regular classes I usually only declare attributes that I myself end up setting and using, so in that case an unused attribute really is unused and vulture is great at pointing that out.

Another good example for external APIs is enums. I might have an enum of strings, which might only be constructed based on a string coming from an external API, in which case I might never reference any of the actual enum values directly.

**Comment by jendrikseipp** [comment]
Thanks for your explanation! I can see the utility of being able to ignore members of all classes that inherit from a given class. However, this is difficult to implement in Vulture, which has no notion of variable scopes. If somebody sees a solution for this, I'm happy to discuss it or review a pull request, though.
