### ISSUE TITLE
False positive example should be updated

### ISSUE THREAD

**Issue by yoichi** [jendrikseipp/vulture#272]
Follow the instruction in README.md with vulture >= 2.1 results:

```
$ vulture dead_code.py
dead_code.py:1: unused import 'os' (90% confidence)
dead_code.py:8: unused variable 'message' (60% confidence)
```

It does not detect

```
dead_code.py:4: unused function 'greet' (60% confidence)
```

as expected since https://github.com/jendrikseipp/vulture/pull/219 eliminates the false positive.

I think it would be good to update the example to something that can still be reproduced.

**Comment by RJ722** [comment]
Thanks for the report, @yoichi! I'll get a fix up for this.

**Comment by jendrikseipp** [comment]
Fixed now. Thanks for the report!
