### ISSUE TITLE
Detect unused local variables?

### ISSUE THREAD

**Issue by ChillarAnand** [jendrikseipp/vulture#274]
```
def foo():
	x = 2
	x = 3
	print(x)


print(foo())
```

In the above code, `x = 2` is local unused variable but vulture doesn't detect it currently. May be vulture can detect and report these?

**Comment by jendrikseipp** [comment]
That would be possible, yes, but it would require a substantial amount of changes to the core of Vulture. So currently there are no plans to do that. But I think `flake8` should detect cases like this.
