### ISSUE TITLE
detect public functions that can be private

### ISSUE THREAD

**Issue by uriva** [jendrikseipp/vulture#275]
I think the information vulture has can be used to easily compute functions that can be marked private (`_like_this`) by identifying that they are "dead code" wrt all files except  the one they are in.

This could be very useful.

**Comment by jendrikseipp** [comment]
That's an interesting suggestion, but I think it will lead to too many false positives.

**Comment by uriva** [comment]
the only false positive I can imagine is if they are used outside the repo, but then this is exactly the false positives vulture would return for public functions that are part of the external API.
Am I missing something?
