### ISSUE TITLE
Installing vuture in development environment.

### ISSUE THREAD

**Issue by jack17529** [jendrikseipp/vulture#29]
Readme does not show how to use vulture in development environment.

**Comment by jack17529** [comment]
@jendrikseipp assign me this issue.

**Comment by jendrikseipp** [comment]
If you want you can prepare a PR with your proposed changes, but I'm unsure what you're proposing, so it might not get merged.

**Comment by jack17529** [comment]
So which development environment should we use @jendrikseipp ?

**Comment by jack17529** [comment]
I think virtual environment will be the best.

**Comment by jendrikseipp** [comment]
Of course, but this is the same for any python module, so it doesn't 
need to be documented in the vulture README.
