### ISSUE TITLE
[feat] Support setup.cfg configuration file

### ISSUE THREAD

**Issue by qcoumes** [jendrikseipp/vulture#295]
It would be great if `vulture` also supports a `setup.cfg` configuration file file, or at least has an argument taking a path to a configuration file.

A lot of project uses `setup.cfg` and a lot of tools support it (`pytest`, `flake8`, `pydocstyle`, `pycodestyle`, ...)

**Comment by jendrikseipp** [comment]
Thanks for the suggestion, but for code simplicity we consider this feature out of scope.
