### ISSUE TITLE
Ignore subclasses

### ISSUE THREAD

**Issue by jonnyarnold** [jendrikseipp/vulture#301]
Hi! Thanks for Vulture, it's making it super-easy to get rid of unused code in our large Django project.

Django has a number of APIs that rely on using class definitions as a way of defining elements:
- [Django Admin](https://docs.djangoproject.com/en/4.1/ref/contrib/admin/#modeladmin-options) uses class attributes to customise the way an admin page is displayed.
- [Django Forms](https://docs.djangoproject.com/en/4.1/ref/forms/api/) uses custom class attributes to define fields in Python; these are converted to their respective HTML when rendered on a page. (Their values are typically *not* accessed through these class attributes.)
- [Django Models](https://docs.djangoproject.com/en/4.1/topics/db/models/#meta-options) uses a `Meta` inner class within a `Model` class to customise how the model will behave.

I was wondering how difficult it would be to ignore classes that *sub-class* a particular class? This would allow me to ignore e.g. `Form` and `Model`.

Thanks 🙂

**Comment by jendrikseipp** [comment]
Thanks for the report. I think the underlying problem is identical to #264.
