### ISSUE TITLE
Make vulture available as a library

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#31]
Reference: [coala vulture project](https://projects.coala.io/#/projects?project=vulture_dead_code_removal)

IMO, what we implicate when we say that make vulture available as a library is to perhaps extend the functionality of vulture to be directly incorporated in code, rather than just as a command line feature.
But we already have `vulture.scan()` for that, so I am a little confused on what else do we need here?

**Comment by jack17529** [comment]
@RJ722  first read the code , don't file any issues before that

**Comment by jendrikseipp** [comment]
This is a duplicate of #23. Let's continue the discussion there.
