### ISSUE TITLE
Include code from `coverage.xml`

### ISSUE THREAD

**Issue by sobolevn** [jendrikseipp/vulture#316]
Hi! Thanks for the cool project!

I think that `vulture` can improve its detection skills by a huge margin if coverage generated by `coverage` / `pytest-cov` is taken into an account.

This way `vulture` can know what code was actually called. Of course, the result will dependend on the amount of coverage %, but users can improve their coverage and the process is well-known.

**Comment by RJ722** [comment]
Hi @sobolevn, thanks for your comment. This was discussed thoroughly in #109, but was [closed](https://github.com/jendrikseipp/vulture/issues/109) in favour of maintaining simplicity.
