### ISSUE TITLE
Add test for whitelist.py

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#32]
While writing a test case for whitelist_python.py, I realised that we can potentially write a test case that can check whether or not *whitelisting* works or not and would it give an error if whitelist.py is not supplied!

Is it feasible to do so @jendrikseipp?

**Comment by jack17529** [comment]
What are you trying to tell vulture works the way you like it -

If you want you can use -
$ vulture myscript.py

Or if you want you can use 
$vulture myscript.py whitelist.py

Your issue does not make any sense .

**Comment by jack17529** [comment]
Please first read the code don't file hypothetical issues.

**Comment by jendrikseipp** [comment]
In `test_script.py` there is already a function that tests missing files: `test_missing_file()`. I don't think we need additional tests. Keep in mind that for vulture there is no difference between "normal" Python files and whitelist Python files.

**Comment by RJ722** [comment]
>If you want you can use -
$ vulture myscript.py

What if `myscript.py` contains functions which are needed to be whitelisted? -  we would need `whitelist.py` as you stated: 
> Or if you want you can use
$vulture myscript.py whitelist.py

that's why we are creating a test for it :smile: 

> Your issue does not make any sense .

Please don't be so rude while giving critique! :confused:
