### ISSUE TITLE
Make whitelist configurable

### ISSUE THREAD

**Issue by mssalvatore** [jendrikseipp/vulture#327]
I'd like to be able to configure the path to my vulture whitelist in pyproject.toml. At the present time, it appears that vulture must be invoked like `vulture TARGET WHITELIST_FILE` if you'd like items in the whitelist to be ignored. I'd like to be able to configure `path` and `whitelist` in my pyproject.toml so that I can simply invoke `vulture`.

Thanks!

**Comment by jendrikseipp** [comment]
You can set the `paths` variable in `pyproject.toml` to achieve this: `paths = [TARGET, WHITELIST_FILE]`

**Comment by mssalvatore** [comment]
Thanks!
