### ISSUE TITLE
Mistake in calling function

### ISSUE THREAD

**Issue by jack17529** [jendrikseipp/vulture#33]
When you assign a function to a variable you don't use the () but simply the name of the function.
In your case given def x(): ..., and variable silly_var you would do something like this:
silly_var = x
and then you can call the function either with
x()
or
silly_var()

In test_scavenging.py
func is written instead of func().

**Comment by jendrikseipp** [comment]
The code actually tested that a function is counted as "used" even if it is only referenced or assigned to another name wihtout being called. The code is therefore "correct" and doesn't need to be changed.

**Comment by jack17529** [comment]
As you say @jendrikseipp
