### ISSUE TITLE
Help with ignoring decorated method

### ISSUE THREAD

**Issue by elParaguayo** [jendrikseipp/vulture#336]
Hi there, I'm struggling to ignore an error flagged by vulture.

In my code I have the following method:

```python
from dbus_next.service import method

...

@method()
def RegisterWindow(self, windowId: "u", menuObjectPath: "o"):  # type: ignore  # noqa: F821, N802, N803
    pass
```
vulture reports `unused variable 'menuObjectPath' (100% confidence)`. I don't want to change the name as it's part of a spec so I have added the following line to `[tool.vulture]` in my `pyproject.toml` file: `ignore_decorators = ["@method"]`. However, vulture is still reporting the error. I've tried adding parentheses too with the same result.

Have I missed something obvious?

**Comment by jendrikseipp** [comment]
Vulture just ignores the method name, not the argument names. We're currently debating whether this should be changed in an issue.

**Comment by elParaguayo** [comment]
I got caught out by a google search which included this `"Additionally, the --ignore-decorators option can be used to ignore functions decorated with the given decorator."`

Thanks for the reply.

**Comment by elParaguayo** [comment]
It does actually say that on PyPI so you may want to fix that at some point.

**Comment by jendrikseipp** [comment]
Good point, thanks! Done.
