### ISSUE TITLE
finding completely dead files

### ISSUE THREAD

**Issue by tansaku** [jendrikseipp/vulture#338]
Hi there, great project!

We've had a problem recently in our codebase with some completely dead files that were not imported anywhere, and were not being run by any tests, but coverage.py still said we have 100% coverage. 

Can vulture detect completely dead python files that are not used at all?

Many thanks in advance
Best, Sam

**Comment by jendrikseipp** [comment]
Yes, Vulture will report any names that are defined in the dead file but not used in the dead file.
