### ISSUE TITLE
Switch to tomli/tomllib for toml parsing

### ISSUE THREAD

**Issue by sacsar** [jendrikseipp/vulture#339]
Due to https://github.com/uiri/toml/issues/270, vulture won't run for projects with a `pyproject.toml` that contain an array with mixed types. According to https://github.com/python-poetry/poetry/issues/7094#issuecomment-1328127456, this is not an issue in the `tomllib` in Python 3.11+ or its backport (https://github.com/hukkin/tomli).

It looks like this should be a quick swap. I'll send a PR along when I have a moment.

**Comment by jendrikseipp** [comment]
Sounds good!

**Comment by sacsar** [comment]
A bit more involved than I expected, but the PR is up.
