### ISSUE TITLE
The conda package for `vulture` is unmaintained

### ISSUE THREAD

**Issue by Zeitsperre** [jendrikseipp/vulture#355]
It appears that the `conda` package for `vulture` is lagging by several versions: https://github.com/conda-forge/vulture-feedstock/pulls

I'll open a Pull Request here to add a version badge for `conda-forge`, so that that happens less often.

Thanks for building this neat library!

**Comment by jendrikseipp** [comment]
Thanks for the report and the PR! But wouldn't it be better to have some kind of mechanism that informs the maintainers of the conda Vulture package about new Vulture releases? I guess such a system already exists, right?

**Comment by Zeitsperre** [comment]
I maintain a fair number of conda packages, and "watching" the feedstock and getting tagged on bot-generated Pull Requests is usually enough for me. You should add your name to the maintainers list of the conda package! https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-admin-please-add-user-username

If the dependencies aren't changing between versions, there's also the option of enabling auto-merge as well.

**Comment by jendrikseipp** [comment]
Ah, I think we misunderstood each other: I don't have the bandwidth to maintain the Vulture conda-forge. My hope is that someone from the conda community takes up that task.

**Comment by Zeitsperre** [comment]
Gotcha. If the current maintainer (@jakirkham) is willing to extend access to me, I don't mind adding this to the list of projects I help maintain on `conda-forge`.

Once the package is fast-forwarded on `conda-forge`, we can safely merge #356. Would that be an acceptable solution? I'd like to see this project up-to-date in some of my `conda`-only environments.

**Comment by Zeitsperre** [comment]
@jakirkham I just need your approval and merge here (https://github.com/conda-forge/vulture-feedstock/pull/28) and I can take a few minutes to clean things up. All the best!

**Comment by jendrikseipp** [comment]
This seems to be handled now.
