### ISSUE TITLE
Wanting to contribute: is there a need for a vs code extension that helps you find the unused functions with one click?

### ISSUE THREAD

**Issue by yasserius** [jendrikseipp/vulture#359]
I am sorry is "Issues" isn't the right place to do this.

I was hoping vulture would become more user friendly by integrating better with VS code.

Most recently I used coverage.py and it generated an XML that was compatible with a VS code extension called Code Gutters, that helped visualize unused lines of code easily e.g. you get a list of unused functions, and with one click, it opens up the file and the function, and any other helpful info about the functions usage in that repo.

Maybe we need a UX friendly extension like that for vulture? If so, I could spend some free time contributing to this repo.

**Comment by jendrikseipp** [comment]
That sounds like a great idea! I'm happy to promote the resulting extension in the Vulture README file.

**Comment by yasserius** [comment]
I wanted to ask: when I ran it on a flask app repo, vulture kept finding the view functions as unused, is there a way to ignore these functions? e.g. ignore functions with a certain decorator

**Comment by jendrikseipp** [comment]
Yes, you can use --ignore-decorator for this.
