### ISSUE TITLE
Vulture GitHub Action

### ISSUE THREAD

**Issue by gtkacz** [jendrikseipp/vulture#363]
There should be a Vulture GitHub Action for CI/CD pipelines for maintaining code quality across a codebase. For example, Ruff has [ruff-action](https://github.com/chartboost/ruff-action).

**Comment by gtkacz** [comment]
Implementing this on: https://github.com/gtkacz/vulture-action, if you're satisfied feel free to close this issue.

**Comment by jendrikseipp** [comment]
That was quick! Thanks for your work on this! I added a link to the Vulture README.

**Comment by gtkacz** [comment]
It was simple cause your tool is straightforward! Thanks for your work! 😄
