### ISSUE TITLE
Suggestion: Dockerfile and/or GitHub Action

### ISSUE THREAD

**Issue by reneleonhardt** [jendrikseipp/vulture#370]
More users would be inclined to try Vulture if it wouldn't have to be installed, but would just allow to run it as Docker container or GitHub Action.

**Comment by jendrikseipp** [comment]
You're in luck: since a few weeks there's a Vulture GitHub Action: https://github.com/gtkacz/vulture-action

**Comment by reneleonhardt** [comment]
Cool, I didn't see that unoffical link, thank you!
Maybe it would help to transform that last line into a headline providing an example code block similar to
https://github.com/gtkacz/vulture-action#usage
