### ISSUE TITLE
Use stdlib whitelist by default

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#38]
Whitelists are a great way to tackle false positives, but we have to explicitly mention the whitelist fie every time we execute vulture, so **should vulture use whitelist by default?**

**Comment by RJ722** [comment]
IMHO, we can let the user decide - we can have a *configuration file* - For now, it would contain only `whitelist: on/off`,  but it can be easily extended in future for further configuring vulture, if needed.

**Comment by jendrikseipp** [comment]
I think the whitelists/stdlib.py file should be included by default. 
When we have other whitelist files, we can decide how to include them.

**Comment by RJ722** [comment]
For extending `whitelists/stdlib.py` - can there be a definitive way of doing so?

What I had been thinking of was to **test it with major projects** (perhaps trending python projects on github) - this would serve us with two benefits:
* We can identify instances of what should ideally be in our whitelist file - as we may find any lesser known constructs (alike default_property itself).
* We would know of any bugs, if there, in vulture.

Is this approach feasible?

**Comment by RJ722** [comment]
[coala/coala-bears/#1564](https://github.com/coala/coala-bears/issues/1564) will also get addressed through this issues.

**Comment by jendrikseipp** [comment]
I think this is a great idea! Maybe we can even find projects that 
already use vulture or want to use vulture and can work on creating 
whitelists together.

**Comment by RJ722** [comment]
Should we develop a script which downloads the trending project for the day, execute vulture on it and report the errors, if any!
This way we can ensure that we add something to the whitelist daily.
This would be fun and we can keep developing it - perhaps, may be extend it to e-mail the log to the project maintainer and he can get to us that way.

**Comment by jendrikseipp** [comment]
I doubt that this can be automated. In any case, automation should not 
be the first step :-)

**Comment by RJ722** [comment]
:+1: 

Already started with the [localstack](https://github.com/atlassian/localstack) repository - trending today! - [Here](https://pastebin.com/Gge1yp3q)'s the log file - I'll analyze the issues, convey them this notice and add anything suitable to whitelist tomorrow morning.

Don't you think that it is gonna be unmanageable if we continue this way, can you please suggest some better workflow through which we can track our perfomance!

**Comment by jendrikseipp** [comment]
If you have SyntaxErrors like in the log, you're probably using the 
wrong Python version for calling vulture.

Something else to consider: If you're running vulture on a library, most 
functions will obviously be unused. In this case you should include the 
tests.

Before reporting unused code to projects, we should be pretty certain 
that the code is actually unused. Unfortunately, this is quite hard for 
big projects.

**Comment by RJ722** [comment]
Thank you!
I'll take this into account :smile: 

>  Before reporting unused code to projects, we should be pretty certain that the code is actually unused. Unfortunately, this is quite hard for big projects.

Just for the initial phase, can I ask you for personal conformation before sending reports!

**Comment by jendrikseipp** [comment]
Sure.

I think we have to filter out obvious false-positives (and try to add 
them to a whitelist file). Then think it's mostly a question of wording: 
"Bug: You have the following unused code" is bad wording. "Here is a 
list of functions and variables that might be unused" is better.

**Comment by RJ722** [comment]
Hi! @jendrikseipp 
Since we would be continuing this for a long time, it would be unmanageable if we would keep track of the reports in an issue thread - I thought it would be good if we have a devoted repository for the same: [vulture-analysis](https://github.com/RJ722/vulture-analysis).

I have also created an analysis report. Please have a look.

**Comment by jendrikseipp** [comment]
Great idea! I added a README.md file for steps for future reports.

**Comment by RJ722** [comment]
Hi @jendrikseipp 
I added an analysis report for (system-design-primer)[https://github.com/donnemartin/system-design-primer].
I have filed an issue regarding the same - can you please have a look [here](https://github.com/donnemartin/system-design-primer/issues/53). :smile:

**Comment by RJ722** [comment]
Hi @jendrikseipp 
I added an analysis report for [system-design-primer](https://github.com/donnemartin/system-design-primer) and filed an issue regarding the same - can you please have a look. ([Here's](https://github.com/donnemartin/system-design-primer/issues/53) the link)

Thank You! :smile:

**Comment by jendrikseipp** [comment]
Nice! For the next report, I think it's better to just copy paste our report (i.e., the complete file including the intro text) into the issue report. vulture-analysis should probably just be for our communication.

**Comment by jendrikseipp** [comment]
Getting back to the topic of this issue: vulture should use `whitelists/stdlib.py` by default. For now, I don't think we need an option to disable this feature. @RJ722 Feel free to open a pull request for this.

**Comment by RJ722** [comment]
Can we ship `whitelists/stdlib.py` along with vulture?
If so, we can just append `/path/to/whitelists/stdlib.py` in the args! 😛

**Comment by jendrikseipp** [comment]
Yes, that would be a good plan.
