### ISSUE TITLE
How to whitelist vars in context manager's __exit__() method?

### ISSUE THREAD

**Issue by mark-summerfield** [jendrikseipp/vulture#39]
I've just started to use vulture and already found it helpful.

However, I often have context managers where all I want to do is call a cleanup function and let any exception continue to be raised, e.g.:

```python
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
```
But I can't work out how to whitelist exc_type, exc_val, exc_tb. Is it possible?

BTW I think the docs for whitelist.py could be a bit more explicit. Here's one I'm using which I think shows how to do it:
```python
# whitelist.py
from Parser import humanTime, Reader, Chunk, lzw, Normalize
unused = (humanTime, Reader, lzw.readbytes, lzw.writebytes,
          Chunk.height, Normalize.isspace)
unused = len(unused)
```

**Comment by jendrikseipp** [comment]
I'd recommend using

    def __exit__(self, _, _, _):
        self.close()

I think this is the standard Python way to signal unused variables.

We're in the process of growing the whitelists/stdlib.py file. Your whitelist file can be shortened to the following, I think:

    # whitelist.py
    from Parser import humanTime, Reader, Chunk, lzw, Normalize
    (humanTime, Reader, lzw.readbytes, lzw.writebytes, Chunk.height, Normalize.isspace)
