### ISSUE TITLE
Vulture doesn't handle mixins?

### ISSUE THREAD

**Issue by audiolion** [jendrikseipp/vulture#42]
If I have a mixin with some base code that is going to be used by a number of classes

```

MyMixin(object):

  def check_status(self):
      return ...

MyClass(MyMixin):
  ....

```

Vulture seems to complain that `check_status` is an unused function

edit: maybe this is because `check_status` is called by another mixin

```

# some.third.party
MyOtherMixin(object):

  def check_object(self):
    status = self.check_status()
    ...

# local.py
from some.third.party import MyOtherMixin

MyClass(MyMixin, MyOtherMixin):
  ...
```

**Comment by jendrikseipp** [comment]
Well, it seems none of the subclasses actually call `check_status`. If 
it's still a false-positive, you may consider providing an extra 
whitelist Python file that explicitly "calls" `check_status`.

**Comment by audiolion** [comment]
yeah, this happens a lot in Django CBV's. A lot of people argue the implementation is pretty flawed because there is a ton of implicit calls/variables that are used and assigned that are not seen in the code. But running vulture it threw tons of false positives for all my class based views

**Comment by jendrikseipp** [comment]
Nothing much a static analyzer like vulture can do about this, I guess. The only solution would be to collect implicitly-called methods in a dedicated Django whitelist file.

**Comment by audiolion** [comment]
Ok thanks, closing this
