### ISSUE TITLE
PermissionError on scavenging a file in python3.5.1

### ISSUE THREAD

**Issue by jfrfonseca** [jendrikseipp/vulture#43]
When attempting to scavenge a file, raises a PermissionError when attempting to open /etc/cups/ssl

**Comment by jendrikseipp** [comment]
Could you post the commandline output, please? I guess you'll have to 
exclude files and directories for which you don't have read permissions.

**Comment by jfrfonseca** [comment]
Output of error:

---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-2-d20cda2fa2e6> in <module>()
     13 
     14             obj_vulture = Vulture(verbose=True)
---> 15             obj_vulture.scavenge(diretorio + "/" + arquivo)
     16 
     17             mapa_atributos = obj_vulture.used_attrs_tree

/home/jose/Projetos MXT/vulture/vulture.py in scavenge(self, paths)
    167 
    168     def scavenge(self, paths):
--> 169         modules = self._get_modules(paths)
    170         included_modules = []
    171         for module in modules:

/home/jose/Projetos MXT/vulture/vulture.py in _get_modules(self, paths, toplevel)
    161                     os.path.join(path, filename)
    162                     for filename in sorted(os.listdir(path))]
--> 163                 modules.extend(self._get_modules(subpaths, toplevel=False))
    164             elif toplevel:
    165                 sys.exit('Error: %s could not be found.' % path)

/home/jose/Projetos MXT/vulture/vulture.py in _get_modules(self, paths, toplevel)
    161                     os.path.join(path, filename)
    162                     for filename in sorted(os.listdir(path))]
--> 163                 modules.extend(self._get_modules(subpaths, toplevel=False))
    164             elif toplevel:
    165                 sys.exit('Error: %s could not be found.' % path)

/home/jose/Projetos MXT/vulture/vulture.py in _get_modules(self, paths, toplevel)
    161                     os.path.join(path, filename)
    162                     for filename in sorted(os.listdir(path))]
--> 163                 modules.extend(self._get_modules(subpaths, toplevel=False))
    164             elif toplevel:
    165                 sys.exit('Error: %s could not be found.' % path)

/home/jose/Projetos MXT/vulture/vulture.py in _get_modules(self, paths, toplevel)
    160                 subpaths = [
    161                     os.path.join(path, filename)
--> 162                     for filename in sorted(os.listdir(path))]
    163                 modules.extend(self._get_modules(subpaths, toplevel=False))
    164             elif toplevel:

PermissionError: [Errno 13] Permission denied: '/etc/cups/ssl'

**Comment by jfrfonseca** [comment]
Sample code used:

```
for diretorio, subdirs, arquivos in os.walk(os.getcwd()):
    for arquivo in arquivos:
        
        if arquivo.endswith(".py"):
            
            print(diretorio + "/" + arquivo)
            
            obj_vulture = Vulture(verbose=True)
            obj_vulture.scavenge(diretorio + "/" + arquivo)
```

**Comment by jfrfonseca** [comment]
The forbidden directories are some of the OS's own files, part of the python parse tree, I guess.

**Comment by jendrikseipp** [comment]
Well, I think you are probably executing your script in the root 
directory "/", right? You will probably have to execute it somewhere 
where you have read access.

BTW: vulture will also walk down the directory hierarchy by itself. No 
need for your custom script, I think. Just call vulture with the 
directories you want checked.

**Comment by jfrfonseca** [comment]
It does not work when importing the package as a library in the target directory. Notheneless, it works as advertised when used in the manner described in the README.
