### ISSUE TITLE
unused functions' parameters and unused variables having same names are not reported.

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#47]
For example. running vulture on the following file:
```python
first_name = "Rahul"
sur_name = "Jha"

def say_hello(first_name, sur_name):
	# first_name and sur_name are not reported
	pass

```
we would have following results:
```
dead.py:1: Unused variable 'first_name'
dead.py:2: Unused variable 'sur_name'
dead.py:4: Unused function 'say_hello'
```
It should also report that `first_name`, `sur_name` in `line 4` are not being used as in this case:
```python
first_name = "Rahul"
sur_name = "Jha"

def say_hello(a, b):
	# first_name and sur_name are not reported by vulture
	pass
```
which would produce:
```
dead2.py:1: Unused variable 'first_name'
dead2.py:2: Unused variable 'sur_name'
dead2.py:4: Unused function 'say_hello'
dead2.py:4: Unused variable 'a'
dead2.py:4: Unused variable 'b'
```

Is this a bug?

**Comment by jendrikseipp** [comment]
This behaviour is to be expected since vulture doesn't distinguish between "local variables" and "parameter variables". We could actually distinguish between the "defined variable" and "defined parameter". Currently, vulture uses (in line 300)

        elif isinstance(node.ctx, (ast.Param, ast.Store)):
            self._define_variable(node.id, node.lineno)

We would need separate lists for "defined variables" and "defined parameters" and split the "elif" into two "elifs" for ast.Store and ast.Param. However, I don't see an easy way for distinguishing between "used variable" and "used parameter". Therefore, we can't detect unused parameters.

**Comment by SmartManoj** [comment]
> dead2.py:4: Unused variable 'a'
> dead2.py:4: Unused variable 'b

Isn't a and b are unused params?

**Comment by SmartManoj** [comment]
```
t.py:1: unused variable 'first_name' (60% confidence)
t.py:2: unused variable 'sur_name' (60% confidence)
t.py:5: unused function 'say_hello' (60% confidence)
t.py:5: unused parameter 'first_name' (100% confidence)
t.py:5: unused parameter 'sur_name' (100% confidence)
```

**Comment by SmartManoj** [comment]
```
code = """
first_name = "Rahul"
sur_name = "Jha"


def say_hello(first_name, sur_name3):
    # first_name and sur_name are not reported
    print(first_name)
    pass
"""


import ast
import ast_scope
tree = ast.parse(code)
from pprint import *
pprint(ast.dump(tree))
variable = tree.body[0].targets[0]
parameter = tree.body[2].body[0].value.args[0]
# print(ast.dump(a))
scope_info = ast_scope.annotate(tree)
print(scope_info[variable])
print(scope_info[parameter])

```

Output:
```
<ast_scope.scope.GlobalScope object at 0x0000015AB47FB580>
<ast_scope.scope.FunctionScope object at 0x0000015AB47FB340>
```
