### ISSUE TITLE
Implement confidence values

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#48]
It would be nice if vulture reports a confidence value associated with every result.

Strategy for calculating confidence values:
* `imports` are reported with 100% confidence
* Anything we are not sure about should be reported with 50% confidence
* `*` imports should with 0 % confidence

| Construct | Confidence |
|     :---:      |          :---:    |
|import	| 100%|
|from foo import *	|0%|
|variable	|50%|
|function	|50%|
|class	|50%|

**Comment by jendrikseipp** [comment]
What's the status on this?

**Comment by RJ722** [comment]
I am sorry for the late reply, I don't know how come this didn't show up in my notifications.

Well, I am done with the basic functionality, it's just I am trying to differentiate between `*` imports and normal imports.
I should raise a PR anyway 😛 .

**Comment by RJ722** [comment]
Now, when I look into it, `vulture` doesn't reports `*` imports, so we don't need to do anything. Simply associate 100% confidence with `imports`. 😄

**Comment by jendrikseipp** [comment]
I have thought about this some more and came to the conclusion that, at least for now, we should add the confidence values where they're actually needed, i.e. in the VultureBear.

**Comment by RJ722** [comment]
Can we reopen this @jendrikseipp ?

Confidence values:
* Unreachable code - 1.0
* Unused import - 0.9
* other unused items - 0.6

**Comment by jendrikseipp** [comment]
Sure, good idea. Now that we can detect unreachable code with 100% confidence, it makes sense to show these values in the output.
