### ISSUE TITLE
unused for loop variable

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [jendrikseipp/vulture#51]
Hi, I really like this library.

I'm have been getting unused messages about the variable defined by a for loop which is just a place holder.

Ex
```python
for repeat in range(10):
    do something that doesn't use repeat
```

**Comment by jendrikseipp** [comment]
It's a common Python idiom to use "_" for unused variables. Vulture won't complain about unused "_"-variables.

**Comment by BebeSparkelSparkel** [comment]
Thanks that's what I was looking for
