### ISSUE TITLE
Package vulture

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#52]
We need to provide vulture as a package in order to ship additional package data like whitelists, etc.

Directory structure:
```
vulture/
    __init__.py (contains __version__)
    core.py (with the contents from old vulture.py)
```

Refer: https://github.com/jendrikseipp/vulture/pull/50#discussion_r121908392

**Comment by RJ722** [comment]
I think we would need `whitelists/`  in the `vulture` folder, because parent directories (..) are not allowed in the `resource` argument.
Though, this is working for me, I wanted to take a second opinion.

Reference: https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data

**Comment by jendrikseipp** [comment]
* Yes, we should move `whitelists` into the `vulture` folder.
* We can try to use `get_data`, since later in the scavenge function, we need the file's content anyway.
* get_data returns a binary string, make sure to decode it into a unicode string.
