### ISSUE TITLE
There is no requirements file

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#53]
IMHO we should have two files:

`requirements.txt`:
```
pbr==3.0.1
six==1.10.0
stevedore==1.23.0
virtualenv==15.1.0
vulture==0.14
```

`test-requirements.txt`:
```
pluggy==0.4.0
py==1.4.34
tox==2.7.0
```

**Comment by jendrikseipp** [comment]
At first I thought this was a good idea, but I don't see why we need them after reading https://pip.readthedocs.io/en/stable/user_guide/#requirements-files, https://packaging.python.org/discussions/install-requires-vs-requirements/ and https://caremad.io/posts/2013/07/setup-vs-requirement/.
