### ISSUE TITLE
Overriden methods of C/C++ extensions

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/vulture#8]
Originally reported by: **Florian Bruhin (Bitbucket: [The-Compiler](https://bitbucket.org/The-Compiler), GitHub: [The-Compiler](https://github.com/The-Compiler))**

----------------------------------------

When subclassing a method of a class defined in a C/C++ extension, such as this example using the PyQt GUI framework:

```python
from PyQt5.QtCore import QSize
from PyQt5.QtWidgets import QLineEdit, QApplication


class LineEdit(QLineEdit):

    def sizeHint(self):
        return QSize(128, 128)

app = QApplication([])
le = LineEdit()
le.show()
app.exec_()
```

vulture doesn't detect that `sizeHint` is called via C++:

```
foo.py:7: Unused function 'sizeHint'
```

Maybe if a class inherits from a non-Python class, and an existing method is overridden, it should always be considered used?

----------------------------------------
- Bitbucket: https://bitbucket.org/jendrikseipp/vulture/issue/8

**Comment by jendrikseipp** [comment]
I think you mean `tox -e vulture`? 

Maybe the two virtual functions are not explicitly marked as virtual (I don't know how sip files work)?

@The-Compiler, can you help us out here?

**Comment by The-Compiler** [comment]
I agree about the false-positives. `dnsResolve` and `myIpAddress` are exposed to JavaScript via the `@_js_slot` decorator and vulture can't catch that. Dunno about `qCleanupResources`, that's some internal PyQt-thing probably, which is called from C++ but without being actually something from Qt.

I agree about `interceptRequest` and `requestStarted` - those should be virtual. I'm not sure whether it's a bug in the script, or a bug in `sip` somewhere - you can probably tell by reviewing the XML file which gets output by sip.

**Comment by RJ722** [comment]
> I think you mean tox -e vulture?

So sorry, my bad! :-p

> I agree about interceptRequest and requestStarted - those should be virtual. I'm not sure whether it's a bug in the script, or a bug in sip somewhere - you can probably tell by reviewing the XML file which gets output by sip.

I am looking into it.

**Comment by jendrikseipp** [comment]
What's the status here? Can we link to your repo, Rahul and close this issue?

**Comment by RJ722** [comment]
Hey Jendrik,

Ongoing action occurring at https://github.com/RJ722/vulture-whitelist-generators/tree/generate. I've an ongoing [PR](https://github.com/RJ722/vulture-whitelist-generators/pull/1) which is just one final review from @The-Compiler apart from release 1. 😛

**Comment by jendrikseipp** [comment]
Now that we have a repository for whitelist generators at https://github.com/RJ722/vulture-whitelist-generators, I think we can close this issue.
