### ISSUE TITLE
underscore prefix on functions does not prevent an 'unused function' warning.

### ISSUE THREAD

**Issue by timjstewart** [jendrikseipp/vulture#87]
I'm using the Python library Flask for developing routes.

Here is my route:

```
@app.route("/status", methods=['GET'])
def status():
    return "OK", 200
```

This yields this warning:

```
server.py:66: unused function 'status'
```

If I add an underscore prefix to the status function name, I get this warning:

```
server.py:66: unused function '_status'
```

Since the function name is not important to Flask, I can just call the function '_' which yields

```
server.py:66: unused function '_'
```

Is there some way of avoiding this warning?

Thanks!

**Comment by jendrikseipp** [comment]
Prefixing functions with an underscore is not a good solution, I think. A leading underscore signals that a local variable is unused or that a method is "private". I think a better way of avoiding false-positives is to add a whitelist module that "uses" the function and pass it to vulture:

    # Contents of mywhitelist.py:
    import server
    server.status
