### ISSUE TITLE
detect unreachable code if the condition is unsatisfiable

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#88]
As, the TODO file says, it would consists of:

- [X] Detect unreachable code à la while False: (by implementing Vulture.visit_While(self, node).
- [ ] Detect unreachable code à la if False: (by implementing Vulture.visit_If(self, node).
- [X] ~~Detect unreachable else clauses by detecting if True:.~~ (#90)
- [ ] Detect unreachable code for ast.IfExp.
- [X] ~~Detect unreachable code for ast.Assert.~~

**Comment by RJ722** [comment]
> Detect unreachable code for ast.Assert.

Won't assert statements throw up errors if unsatisfied?

**Comment by jendrikseipp** [comment]
`assert False` means that the code is either never reached or will throw an AssertionError when reached. But you're probably right. There may be cases where `assert False` is intended. Let's not try to detect unsatisfiable assert statements.

**Comment by RJ722** [comment]
Hi @jendrikseipp, can we reopen the issue because `if False` statements are yet not reported.

> Detect unreachable code for `ast.IfExp`.

Is this any different from `ast.If`?

**Comment by jendrikseipp** [comment]
Let's do ast.If before we look into ast.IfExp. We can handle ast.IfExp in a separate PR. An example for ast.IfExp is `a = 1 if False else 2`.

**Comment by jendrikseipp** [comment]
I don't think it's worth the effort to catch unsatisfiable ast.IfExp conditions. Therefore, I think we're done here :-)
