### ISSUE TITLE
Filtering items with a regex

### ISSUE THREAD

**Issue by The-Compiler** [jendrikseipp/vulture#92]
I currently have [a custom script](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/dev/run_vulture.py) to run vulture for two reasons:

- Dynamically generating a whitelist.
- Filtering any functions matching `[a-z]+[A-Z][a-zA-Z]+` because those are typically virtual methods provided by Qt/PyQt, i.e. from C++ - any Python methods are named `snake_case` in my project.

Unfortunately, the script broke quite often recently because things changed in vulture in subtle ways. I don't think the whitelist is the problem (after all, I just pass that to vulture), but the filtering means I need to have my own `report` there so I can filter the items before they are reported.

I say two ways around this:

- Adding something like a `--func-filter-regex` (and maybe `--props-filter-regex`, etc.) commandline argument.
- Adding something like a `filter_callback` to `vulture.report`, which is only intended for when using vulture programmatically, and gets called with each `Item` once. If it returns `True`, the given item does not get reported.

Both of those would probably make my script a bit less relying on vulture internals. For the first one, I could even switch to running `vulture.main`.

What do you think?

**Comment by jendrikseipp** [comment]
I think your second solution is better since it allows you greater freedom: using regexes can solve the easiest cases, but will often be insufficient. For example, I can think of scenarios, where you want to take into account the filename in addition to the function name. This solution can be implemented by calling `Vulture.get_unused_code()` and filtering the returned list of `Item`s by inspecting their types and names. 

You can find an example of how to use vulture as a library here: https://github.com/RJ722/coala-bears/blob/12a6e88bd43c0413a70e4f26dc8feb5ca545e7ff/bears/python/VultureBear.py

**Comment by The-Compiler** [comment]
I'm aware, that's what I'm doing currently. Like outlined above, this means I need to reimplement `Vulture.report` (which can break e.g. because `Item.lineno` was renamed).

I'd rather use vulture's `report` function, but this means I need to be able to pass a filter to vulture somehow, or to pass a list of items to `report`.

**Comment by jendrikseipp** [comment]
I think the `report` function should only be used as-is, if vulture is used as a script. Probably, it shouldn't even be a method, but a function outside the Vulture class. I agree that formatting the report lines is tedious and bound to break with vulture upgrades. What do you think about adding a `report` method to `Item` that prints the formatted line to stdout? Then your sutom report() function could be as short as

    def report():
        for item in vulture.get_unused_code():
            # TODO: filter items
            item.report()

**Comment by The-Compiler** [comment]
That sounds like a great idea! Maybe for programmatical use, it should just return the string instead of printing it (maybe call it `format_report()` then?), though for me both is fine. Then the custom report would do `print(item.format_report())` or so.

It probably needs `sort_by_size` passed as well, as the report changes based on that.

**Comment by RJ722** [comment]
A `format_report` function would offer great flexibility. :smile:  

@jendrikseipp can I send a PR?

**Comment by jendrikseipp** [comment]
Sure 🙂 please call the method get_report.

**Comment by The-Compiler** [comment]
Thanks @RJ722! If you do, can you please @mention me or add a comment here so I don't miss it? 👍
