### ISSUE TITLE
Ignore unittest.mock return_value?

### ISSUE THREAD

**Issue by kmarekspartz** [jendrikseipp/vulture#95]
In a file with a bunch of mocks, I'm seeing a bunch of these false positives:

`tests/test_filename.py:555: unused attribute 'return_value' (60% confidence)`

Mocking and dead code don't feel like they go well together...

Ignore this test file for now.

**Comment by jendrikseipp** [comment]
Thanks for the hint. We should add `return_value` (https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.return_value) to the `unittest` whitelist file.
